### PR TITLE
Add RTL demo and visual tests

### PR DESCRIPTION
**Pull request by limonte**
It should be easy to add support for ~ **250 million** of Arabic speakers + ~ **10 milion** of Hebrew speakers.

RTL support is straightforward and implementation effort is relatively low since all browsers support that well.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/134)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 203 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/134#-KtW5H8uHLq_JJ4qn1EH:-KtW5H8uHLq_JJ4qn1EI:b-2h1th6) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c6a71a1319934bbb52741c602bd4f82e03df629a/vaadin-text-field.html#L203)):*
> ```HTML
>              * rtl: right to left.
>              */
>             dir: {
> ```

I'm not that familiar with the spec but obviously rlt should be assignable in the body tag https://github.com/vaadin/vaadin-date-picker/issues/421

Maybe we can skip adding individual `dir` properties to our elements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/134)*

**Comment by limonte** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 203 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/134#-KtW5H8uHLq_JJ4qn1EH:-KtW9jHYbXcF8OtEMWqv:b-tmdyvm) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c6a71a1319934bbb52741c602bd4f82e03df629a/vaadin-text-field.html#L203)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I'm not that familiar with the spec but obviously rlt should be assignable in the body tag https://github.com/vaadin/vaadin-date-picker/issues/421

Maybe we can skip adding individual `dir` properties to our elements.
</blockquote></details>

We don't need the property indeed. Users just need to add `dir="rtl"` to any container (`html`, `body`, `div.container`, etc.) and everything should just work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/134)*

**Comment by jouni** [comment]
If a theme wants to do adjustments based on the language direction, I wonder how that would be possible then?

**Comment by limonte** [comment]
> If a theme wants to do adjustments based on the language direction, I wonder how that would be possible then?

Unfortunately, seems to me like impossible without some tricky workarounds.

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 5 of 8 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/134#-:-KtpOsZ-5bdtZ7xA20Ga:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 5 of 8 files at r1, 2 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/134#-:-Kttrpn4BspXE_bqFmdQ:bnfp4nl)*

**Pull request merged**
