### PR TITLE
Prevent invalid input feature

### LINKED ISSUE #27: Prevent invalid input
Use cases:
- applies only to sync validation
- opt-in feature to prevent user from typing values that would be invalid
- should of course work with custom validators also
- `iron-input` has a corresponding property called `prevent-invalid-input`

### PR DESCRIPTION
**Pull request by tomivirkki**
Closes #27

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/49)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-:-KgYodZSr9nBta5yToaF:bnfp4nl)*

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 242 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-KgZ4qIN0_yBuRib8DiT:-KgZ4qIOi_FVstsf0FPi:b3iqn0n) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8e3746d1a75ee884a2d8eb12df811e721cb7061c/vaadin-text-field.html#L242)):*
> ```HTML
>         if (this.preventInvalidInput) {
>           const input = this.$.input;
>           if (input.value.length > 0 && !input.checkValidity()) {
> ```

We probably want to call `this.validate()` to support the custom validation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-text-field.html, line 89 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-KgZ6GIq9h5w73UFTf4-:-KgZ6GIrXE2CJ8o_ur7w:b-5hzqat) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8e3746d1a75ee884a2d8eb12df811e721cb7061c/vaadin-text-field.html#L89)):*
> ```HTML
>       title="[[title]]"
>       on-blur="validate"
>       on-input="_onInput"
> ```

Have you notice that validate is called each time the user types something because of the value-changed, it seems that happens once the value has been set, so after blur the first time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49)*

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-text-field.html, line 89 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-KgZ6GIq9h5w73UFTf4-:-KgZ9hxjDGjJ3aYpRmSc:b28z1wt) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8e3746d1a75ee884a2d8eb12df811e721cb7061c/vaadin-text-field.html#L89)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Have you notice that validate is called each time the user types something because of the value-changed, it seems that happens once the value has been set, so after blur the first time
</blockquote></details>

Sure, but we want to prevent invalid input on user action only.

---

*[vaadin-text-field.html, line 242 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-KgZ4qIN0_yBuRib8DiT:-KgZ8fvxq3v6DIy9PovY:bvg12sy) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8e3746d1a75ee884a2d8eb12df811e721cb7061c/vaadin-text-field.html#L242)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

We probably want to call `this.validate()` to support the custom validation
</blockquote></details>

It's not specified to support custom validators. `<iron-input prevent-invalid-input>` doesn't.

Also, `validate()` changes `this.invalid` value (which notifies) as a side effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-text-field.html, line 89 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-KgZ6GIq9h5w73UFTf4-:-KgZBtOEcZ7vH_DvbmPy:b-bk2fz8) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8e3746d1a75ee884a2d8eb12df811e721cb7061c/vaadin-text-field.html#L89)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Sure, but we want to prevent invalid input on user action only.
</blockquote></details>

But check validity is called twice, so the call in value changed could be debounced some way

---

*[vaadin-text-field.html, line 242 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-KgZ4qIN0_yBuRib8DiT:-KgZC8ofL3MOneql9l6P:b-mrmcnm) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8e3746d1a75ee884a2d8eb12df811e721cb7061c/vaadin-text-field.html#L242)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

It's not specified to support custom validators. `<iron-input prevent-invalid-input>` doesn't.

Also, `validate()` changes `this.invalid` value (which notifies) as a side effect.
</blockquote></details>

In my PR I decided not to change this.invalid in validate but in the point where it is called if it is the case of changing the property

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49)*

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-text-field.html, line 89 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-KgZ6GIq9h5w73UFTf4-:-KgZD-7O2keh38LVBRSL:b-69brlz) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8e3746d1a75ee884a2d8eb12df811e721cb7061c/vaadin-text-field.html#L89)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

But check validity is called twice, so the call in value changed could be debounced some way
</blockquote></details>

No need for premature optimization if that's what you're after. Also, as mentioned below, I'm not using `validate()` directly but native `input.checkValidity()` which ignores custom validators

---

*[vaadin-text-field.html, line 242 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-KgZ4qIN0_yBuRib8DiT:-KgZCjr8tPfQEUhOAKcW:bm9axpe) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8e3746d1a75ee884a2d8eb12df811e721cb7061c/vaadin-text-field.html#L242)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

In my PR I decided not to change this.invalid in validate but in the point where it is called if it is the case of changing the property
</blockquote></details>

Sure, but that wasn't the main point of not using it but: "It's not specified to support custom validators. <iron-input prevent-invalid-input> doesn't."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-:-KgZHl7e5WULpeMLik9m:bnfp4nl)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 242 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-KgZ4qIN0_yBuRib8DiT:-KgZMRRpVYfDfJo9ojE9:b6ywllz) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8e3746d1a75ee884a2d8eb12df811e721cb7061c/vaadin-text-field.html#L242)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Sure, but that wasn't the main point of not using it but: "It's not specified to support custom validators. <iron-input prevent-invalid-input> doesn't."
</blockquote></details>

The ticket description says: "should of course work with custom validators also"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49)*

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 242 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-KgZ4qIN0_yBuRib8DiT:-KgZYaCg7NHKqqJXVgkw:b2d7czr) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8e3746d1a75ee884a2d8eb12df811e721cb7061c/vaadin-text-field.html#L242)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

The ticket description says: "should of course work with custom validators also"
</blockquote></details>

Oh damn, missed that :D But still, should it?
To be precise, a concept of “custom validators” was dropped in favour of providing an example on how to implement that with the current API. And since the “custom validator” can be asynchronous as in the example at https://jsfiddle.net/Saulis/eqf2ph1c/, there’s no way we can hook it to this feature.

The spec says that "iron-input has a corresponding property called prevent-invalid-input" and as I mentioned, `<iron-input prevent-invalid-input>` bypasses custom validator also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49)*

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 242 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-KgZ4qIN0_yBuRib8DiT:-Kgmgi4ke1uvoROtELmw:b-1sr85q) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8e3746d1a75ee884a2d8eb12df811e721cb7061c/vaadin-text-field.html#L242)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Oh damn, missed that :D But still, should it?
To be precise, a concept of “custom validators” was dropped in favour of providing an example on how to implement that with the current API. And since the “custom validator” can be asynchronous as in the example at https://jsfiddle.net/Saulis/eqf2ph1c/, there’s no way we can hook it to this feature.

The spec says that "iron-input has a corresponding property called prevent-invalid-input" and as I mentioned, `<iron-input prevent-invalid-input>` bypasses custom validator also.
</blockquote></details>

As described here https://github.com/PolymerElements/iron-validatable-behavior/blob/master/iron-validatable-behavior.html#L24 `validate()` _should_ have side effects (invalid & aria-invalid attribute).

Extracted the `checkValidity()` call to a shared `_getValidity()` function used by both the `validate()` and "prevent invalid input" feature.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49)*

**Comment by manolo** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-text-field.html, line 262 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-Kgn0_Y9IVe6Ofj1S57n:-Kgn0_YAW577z22Pwe6L:b-myfm5l) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5ac616f4609a7413e6fbfd9b25a412582eab55e3/vaadin-text-field.html#L262)):*
> ```HTML
>        */
>       validate() {
>         return !(this.invalid = !this._getValidity());
> ```

I don't think the validate() method should change the invalid flat. In my PR, invalid is set when it is convenient, so we don't need the _getValidity and the public method could be called anytime without changing the visual appearance. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49)*

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 262 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-Kgn0_Y9IVe6Ofj1S57n:-Kgn5NByLDJKbGJLDpLV:bulntwi) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5ac616f4609a7413e6fbfd9b25a412582eab55e3/vaadin-text-field.html#L262)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I don't think the validate() method should change the invalid flat. In my PR, invalid is set when it is convenient, so we don't need the _getValidity and the public method could be called anytime without changing the visual appearance. 
</blockquote></details>

It should according to https://github.com/PolymerElements/iron-validatable-behavior/blob/master/iron-validatable-behavior.html#L24

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49)*

**Comment by manolo** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-text-field.html, line 262 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-Kgn0_Y9IVe6Ofj1S57n:-KgnGYcySPrIoU4G91Tz:bqkic6e) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5ac616f4609a7413e6fbfd9b25a412582eab55e3/vaadin-text-field.html#L262)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

It should according to https://github.com/PolymerElements/iron-validatable-behavior/blob/master/iron-validatable-behavior.html#L24
</blockquote></details>

But in their implementation (at least with iron-input) they don't assume that someone can override the validate method like we do.
Actually when they implement validate, they use an event for the user to custom validate and we  do not.

So if we encourage people to use extension, we need to notice them to handle the invalid flag by hand, each time validate is called. But it could be interesting to change the flag like in a proper form validation, or not like in your checkValidity case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49)*

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 262 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-Kgn0_Y9IVe6Ofj1S57n:-KgnLmzDu7wK8pgZYy9x:b-9tg86x) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5ac616f4609a7413e6fbfd9b25a412582eab55e3/vaadin-text-field.html#L262)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

But in their implementation (at least with iron-input) they don't assume that someone can override the validate method like we do.
Actually when they implement validate, they use an event for the user to custom validate and we  do not.

So if we encourage people to use extension, we need to notice them to handle the invalid flag by hand, each time validate is called. But it could be interesting to change the flag like in a proper form validation, or not like in your checkValidity case.


</blockquote></details>

We don’t assume people override `validate()` either. It’s for `<iron-form>`’purposes. If you want to implement custom validation, you should consider overriding `checkValidity` instead (or whatever, not in scope of this PR to decide). The documentation I linked also states you shouldn’t override `validate()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-text-field.html, line 262 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-Kgn0_Y9IVe6Ofj1S57n:-KgnPI001tV6GoXec-2f:bcr4mba) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5ac616f4609a7413e6fbfd9b25a412582eab55e3/vaadin-text-field.html#L262)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

We don’t assume people override `validate()` either. It’s for `<iron-form>`’purposes. If you want to implement custom validation, you should consider overriding `checkValidity` instead (or whatever, not in scope of this PR to decide). The documentation I linked also states you shouldn’t override `validate()`
</blockquote></details>

Yes, we'll instruct our users to override `checkValidity()` in most cases. Some cases like async validation require overriding `validate()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/49#-:-KgnPa4mkfqstPDooMDj:bnfp4nl)*

**Pull request merged**
