### PR TITLE
Prevent mousedown event on reveal-button

### LINKED ISSUE #147: Regression: Toggling the eye-icon steals focus from the input
`<vaadin-password-field>` issue only

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #147

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/151)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-password-field.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/151#-KvlWP5qyk_z_emcsiPx:-KvlWP5qyk_z_emcsiPy:b-4y60i9) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/811f60e1f4e6393aeb8f94b679c90e200544e795/vaadin-password-field.html#L49)):*
> ```HTML
>     <div
>       part="reveal-button"
>       on-mousedown="_preventDefault"
> ```

Should be tested to prevent regressions.

---

*[vaadin-password-field.html, line 149 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/151#-KvlWKtQseF9SkARVGk6:-KvlWKtQseF9SkARVGk7:bakuvad) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/811f60e1f4e6393aeb8f94b679c90e200544e795/vaadin-password-field.html#L149)):*
> ```HTML
>         }
> 
>         _togglePasswordVisibility(e) {
> ```

Unnecessary arguments change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/151)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-password-field.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/151#-KvlWP5qyk_z_emcsiPx:-KvlcnKoOxHv4-gBnQLk:b-65kv61) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/811f60e1f4e6393aeb8f94b679c90e200544e795/vaadin-password-field.html#L49)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Should be tested to prevent regressions.
</blockquote></details>

Test added.

---

*[vaadin-password-field.html, line 149 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/151#-KvlWKtQseF9SkARVGk6:-KvlckonmOkjih51W0Kr:b4gpzv8) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/811f60e1f4e6393aeb8f94b679c90e200544e795/vaadin-password-field.html#L149)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Unnecessary arguments change.
</blockquote></details>

Sorry, made by mistake. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/151)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/151#-:-Kw-06VtUAlyWRWPM1L3:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/151#-:-Kw-dj6iZY0I63sM5jHc:bg7igkv)*

**Pull request merged**
