### PR TITLE
Add has-label attribute for styling

### LINKED ISSUE #186: Reflect label as a state attribute
- Add a test
- Add to documentation
- Update analysis.json

This fix is need by some Lumo selectors. For example: https://github.com/vaadin/vaadin-text-field/blob/master/theme/lumo/vaadin-text-field.html#L51

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #186

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/194)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[src/vaadin-text-field.html, line 93 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/194#-L37LftGlHEDpPC04fko:-L37LftGlHEDpPC04fkp:b-a2b411) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/e3e205861b5ffbb21dd912dca1b97df1c5c3f963/src/vaadin-text-field.html#L93)):*
> ```HTML
>        * `disabled` | Set to a disabled text field | :host
>        * `has-value` | Set when the element has a value | :host
>        * `label` | Set when the element has a label | :host
> ```

After reconsidering, would it make more sense to align the behaviour with that of `value` and just mark the element with `has-label`. The value of the `label` property is irrelevant for the theme.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/194)*

**Comment by web-padawan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-text-field.html, line 93 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/194#-L37LftGlHEDpPC04fko:-L37XlwGghnT2KhrxXP0:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/e3e205861b5ffbb21dd912dca1b97df1c5c3f963/src/vaadin-text-field.html#L93)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

After reconsidering, would it make more sense to align the behaviour with that of `value` and just mark the element with `has-label`. The value of the `label` property is irrelevant for the theme.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/194)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/194#-:-L37Yl5veC3HdorWvOQw:bnfp4nl)*

**Comment by platosha** [comment]
Now that `has-label` makes us to edit the theme anyway, would it rather make sense to simply hide the `<label>` when it’s text is empty?

If done this way, the theme can define spacing in a more straightforward way, without having to use selectors like `[label]`. No API changes required.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/194#-:-L37ZoulPh-5feFUJNij:bfwd0fu)*

**Comment by web-padawan** [comment]
After discussing we came up to conclusion that adding `has-label` would make things complex from the a11y point of view when using in`vaadin-form-layout` with the external label.

@jouni what if we just set`position: absolute` on the label part and `align-items: baseline;` on the host element? It appears to be simpler than the current implementation with two nested flex containers and pseudo element pushing element without label to fit baseline. The drawback is that we would still need to add `margin-top` for element having label, and with the absolute positioning this is not possible.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/194#-:-L37chQzRq4WXR4XNr6l:b-23zo9d)*

**Comment by jouni** [comment]
I’m not in favor of moving the limitation on the conditional margin (based on the existence of a label).

> Now that has-label makes us edit the theme anyway, would it rather make sense to simply hide the <label> when it’s text is empty?

This is what I actually wanted to do in Lumo in the beginning, but since the default value was previously `undefined` the `<label>` element was never empty even if no label was specified. Then I change the default value to `''` and made the dependent elements bind to the `label` attribute instead of the property.

But I learned that we can use `null` as the default value, and everything should work nicely after that. There’s already `[part="label"]:empty { display: none; }` in Lumo. I suppose we can then revert back to binding to the `label` property in the dependent elements, if wanted.

**Comment by web-padawan** [comment]
So it appears that preserving the `margin` on the element depending on whether it has label or not would still require us to have this attribute, and the `vaadin-material-theme` relies on it as well for some transitions: https://github.com/vaadin/vaadin-material-theme/blob/master/vaadin-text-field.html#L111

**Comment by platosha** [comment]
Right, explicit `[has-label]` is good to have then :thumbsup: 

:lgtm: 

---

Reviewed 1 of 7 files at r1, 6 of 6 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/194#-:-L3CTEV18n5AEnohHVC9:bkifxmv)*

**Pull request merged**
