### PR TITLE
Added 5 star rating badge

### PR DESCRIPTION
**Pull request by binhbbui411**
Hi, your component was tested and listed in our Vaadin Directory with a pretty high rating. We think it would be cool to have these badges in your project.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/220)

### CODE REVIEW

**Comment by tomivirkki** [comment]
PR's such as this, that are supposed to be repeated for every component, should be targeted to vaadin-element-skeleton. Once the PR if approved and merged there, we'll reflect the same change to each individual component repository (without additional PR's)

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-text-field/220#-:-LAmoHscCFISwsUfLk7-:b6qi8vq)*

**Comment by binhbbui411** [comment]
Will do that!

**Comment by binhbbui411** [comment]
@tomivirkki Just did the pull request to vaadin-element-skeleton. Who is in charge of maintaining that repo?

**Comment by tomivirkki** [comment]
The Vaadin components team. Will close this PR now.

**Pull request closed without merging**
