### PR TITLE
Use polymer-cli for serving and testing

### PR DESCRIPTION
**Pull request by limonte**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/43)

### CODE REVIEW

**Comment by manolo** [comment]
This is a pure 2.0 element without variants, we don't need the user to install polymer to run the project, so npm and bower would be enough. Do we encourage users to install polymer-cli for some reason? 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/43#-:-KgTin6l2CznbadcMB72:b-1dlaf6)*

**Comment by limonte** [comment]
Yes, polymer-cli is the "official" tool for serving/testing/building/linting Polymer web-components: https://www.polymer-project.org/2.0/docs/tools/polymer-cli

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/43#-:-KgTkJZvJsIEXFePyr7G:b-py2a8a)*

**Comment by limonte** [comment]
https://youtu.be/HgJ0XCyBwzY

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/43#-:-KgU-4WzVmdT-U0Y3s7i:bjv03qr)*

**Comment by manolo** [comment]
Still not convinced, 1 polymer-cli is in a pre-release status, 2 the official tool for testing is wct and for packaging bower, 
3 this project has not been generated with any official template nor the CLI, 4 npm install polymer-cli installs 224Mb .

So I would say in the readme, install polymer-cli, otherwise you can run wct and bower

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/43#-:-KgUMQ7P0bb8FE4wLqGF:b-sdf36p)*

**Pull request closed without merging**
