### PR TITLE
Rename text field

### LINKED ISSUE #34: Rename to `vaadin-text-field`
As the native `<input>` element has the `type` attribute, which can make the element behave completely differently from a text input (such as "checkbox" and "range"), and since we have `TextField` and `TextArea` components in the Vaadin Framework currently, I think it would be better if we changed the name of this element. Then, it is more natural to create a `<vaadin-text-area>` element for multi-line text.

This would also make comparisons to paper-input less obvious.

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #34 

Will rename repository after PR is ready to be merged.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-input/36)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/36#-:-KecHxTcIQ63eyfIeTOx:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 17 of 19 files at r1, 1 of 2 files at r2.
Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[bower.json, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-input/36#-Ked1iaxUx5M7__7-iuA:-Ked1iaxUx5M7__7-iuB:b-qt8lqi) ([raw file](https://github.com/vaadin/vaadin-input/blob/3e52a150c6fa5cb9ebd1e5dc94e319ab0566a3ce/bower.json#L12)):*
> ```JSON
>     "Vaadin",
>     "input",
>     "text field",
> ```

probably text-field is better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/36)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/36#-:-Keh_3l3KX6szvJfTjDb:bnfp4nl)*

**Comment by Saulis** [comment]
Review status: 18 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/control-state.html, line 18 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-input/36#-KehgPoVDfM8n6Sl_LRZ:-KehgPoVDfM8n6Sl_LR_:b-y2nhdx) ([raw file](https://github.com/vaadin/vaadin-input/blob/e3e33b4f6661971e0300e58501ba7c3c36a82b6c/test/control-state.html#L18)):*
> ```HTML
>     // Temporary fix until we rename repo
>     if (elementName == 'vaadin-input') elementName = 'vaadin-text-field';
> ```

What is this?

And also what are these programmatic imports for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/36)*

**Comment by manolo** [comment]
Review status: 18 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/control-state.html, line 18 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-input/36#-KehgPoVDfM8n6Sl_LRZ:-KehhakhIzl-qIuNgmp_:b-kszjiw) ([raw file](https://github.com/vaadin/vaadin-input/blob/e3e33b4f6661971e0300e58501ba7c3c36a82b6c/test/control-state.html#L18)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

What is this?

And also what are these programmatic imports for?
</blockquote></details>

That is for re-using control-state in other components tests, like in https://github.com/vaadin/vaadin-button/blob/master/test/index.html where vaadin-button is running tests against it's own implementation of its focusable element

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/36)*

**Comment by Saulis** [comment]
:lgtm: I'm gonna rename the repository now.

---

Review status: 17 of 28 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-input/36#-:-KemCbWRDWJ4rELFV_4i:bu0to9w)*

**Comment by manolo** [comment]
Reviewed 18 of 18 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/36)*

**Pull request merged**
