### PR TITLE
Use input field as the scrolling container

### LINKED ISSUE #162: Edge case on Edge: padding with pasting text.
**Steps to repeat:**

1. Copy and paste some text to text-area

1. Repeat step 1 several times

**Outcome:**
You will see a strange padding from the bottom coming from nowhere

**Gif:**
padding

### LINKED ISSUE #163: Visible scrollbar on IE11
**Description:**
The scrollbar is visible by default in IE11 even while stretching the text-area.

**Gif:**
scollbar

### LINKED ISSUE #165: Text area doesn't cover full height of the container
screenshot 2017-11-13 17 17 00

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #163
Fixes #162
Fixes #165

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/166)

### CODE REVIEW

**Comment by platosha** [comment]
Nit: several empty lines contain unnecessary whitespace.



---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/166#-:-Kyulk15WvfWjTJUq0ro:b-hzsq1t)*

**Comment by tomivirkki** [comment]
Fixed

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/166#-:-Kyz4JkDpkVtZpk7aLNB:b-886gsx)*

**Comment by tomivirkki** [comment]
:lgtm: 

---

Reviewed 1 of 23 files at r2, 1 of 2 files at r3, 21 of 22 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/166#-:-Kz-1ChqLmiayYXvrpnR:bg7igkv)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3, 21 of 22 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/166#-:-Kz-Am3Mqs5M-O3v-wbB:bnfp4nl)*

**Pull request merged**
