### PR TITLE
Simplify dom structure

### LINKED ISSUE #60: Simplify internal structure
- Drop the `label-and-input-container` so that the `content-wrapper` ends up with only `prefix`, `input` and `suffix`.
- Replace `label-placeholder` with the actual `label`
- Consider dropping the outer `container` wrapper

### PR DESCRIPTION
**Pull request by tomivirkki**
Closes #60

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/62)

### CODE REVIEW

**Comment by Saulis** [comment]
The input field seems to have different widths on different browsers on the "short text field with prefix and suffix" visual tests?

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/62#-:-KhahyzEaHPKxtgm1BPb:bw47ae6)*

**Comment by manolo** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/62#-Khai6jCKcPxglwM5m4q:-Khai6jCKcPxglwM5m4r:b-ccyl4y) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/afaeffab72aaad5ad0660d2a05fd3fc9ff8a5d50/vaadin-text-field.html#L55)):*
> ```HTML
> 
>         <input id="input" part="input"
>         autocomplete$="[[autocomplete]]"
> ```

These attributes should be indented 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/62)*

**Comment by tomivirkki** [comment]
Good catch, fixed

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/62#-Khai6jCKcPxglwM5m4q:-Khal52z4VGH2UjwVw88:bw20id4) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/afaeffab72aaad5ad0660d2a05fd3fc9ff8a5d50/vaadin-text-field.html#L55)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

These attributes should be indented 
</blockquote></details>

Oops, fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/62#-:-Khal1TRKG6-IqKoGFie:b-4b5g9p)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: 8 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/62#-:-KhaoZsHnv9Xuk2rW1Y-:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/62)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 8 of 11 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/62#-:-Khb517nf1VEvhxjFcoS:bnfp4nl)*

**Pull request merged**
