### PR TITLE
Include vaadin-themable-mixin

### LINKED ISSUE #45: Theming Support
Add mixin from: https://github.com/vaadin/vaadin-themes/issues/4

### PR DESCRIPTION
**Pull request by tomivirkki**
Closes #45

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/55)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 136 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/55#-Kgy1hUuN0m56Eob7okX:-Kgy1hUuN0m56Eob7okY:b3wcch0) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/338a18139084b1fe3a54cdff674553fca4872072/vaadin-text-field.html#L136)):*
> ```HTML
> 
>   <script>
>     class VaadinTextFieldElement extends Vaadin.ControlStateMixin(Vaadin.FormElementMixin(Vaadin.ThemableMixin(Polymer.Element))) {
> ```

I guess, we need a test that demonstrates that we are extending the themable mixin, otherwise any unintentional removal of the extension would not break tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/55)*

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 136 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/55#-Kgy1hUuN0m56Eob7okX:-Kgy2HDV9mJQYU63DA1l:b7c85i3) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/338a18139084b1fe3a54cdff674553fca4872072/vaadin-text-field.html#L136)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I guess, we need a test that demonstrates that we are extending the themable mixin, otherwise any unintentional removal of the extension would not break tests
</blockquote></details>

Not necessary in this PR. The first included style module that uses the mixin will cover that in visual tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/55)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-text-field.html, line 136 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/55#-Kgy1hUuN0m56Eob7okX:-KgyItPmHDfYAa1uASTb:bq0ncok) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/338a18139084b1fe3a54cdff674553fca4872072/vaadin-text-field.html#L136)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Not necessary in this PR. The first included style module that uses the mixin will cover that in visual tests.
</blockquote></details>

sounds good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/55#-:-KgyIyLl8cOPpeRaVOUj:bnfp4nl)*

**Comment by tomivirkki** [comment]
For some strange reason the visual tests are broken on FF. It looks like the element doesn't get upgraded at all, locally it works fine. Investigating...

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/55#-:-KgyJ7StrdUZOnReFapw:b-x2nhnc)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/55)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/55)*

**Pull request merged**
