### PR TITLE
Styling example

### LINKED ISSUE #59: Theming Example
- Main purpose is to document using the all "parts" for theming.
- List all the parts in the API docs (vs. the old CSS mixins)
- Let's use Bootstrap as inspiration for visual end result
- Add also visual regression testing to make sure each "part" works

### LINKED ISSUE #65: Change .input-wrapper to part="input-field"
- Include in the visual test "styling" suite
- Add to apidocs

### PR DESCRIPTION
**Pull request by tomivirkki**
Closes #59
Closes #65 

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/66)

### CODE REVIEW

**Comment by jouni** [comment]
Should rename part=input to part=value at the same time (as it was the most common name used by the initial test group).

**Comment by tomivirkki** [comment]
@jouni Done.

**Comment by Saulis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/visual/screens/vaadin-text-field/styling/default/chrome.png, line 0 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/66#-Ki-a9JG1CgQLwDHNTzs:-Ki-a9JG1CgQLwDHNTzt:b-se5tyw) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/9ec77b5d4bab68ad0f5bd71598d185a1ef57c983/test/visual/screens/vaadin-text-field/styling/default/chrome.png#L0)):*
Can we fix these cropping issues by wrapping the `vaadin-text-field` with a `<div>` and targeting the screenshots on the wrapping element?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/66)*

**Comment by tomivirkki** [comment]
*[test/visual/screens/vaadin-text-field/styling/default/chrome.png, line  at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/66#-Ki-a9JG1CgQLwDHNTzs:-Ki-ayzo2zzIO1RU8kSc:b-58gqco) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/9ec77b5d4bab68ad0f5bd71598d185a1ef57c983/test/visual/screens/vaadin-text-field/styling/default/chrome.png#L)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Can we fix these cropping issues by wrapping the `vaadin-text-field` with a `<div>` and targeting the screenshots on the wrapping element?
</blockquote></details>

Hmm...what cropping issues?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/66)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: 7 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/66#-:-Ki-cTLNgfD5Rq0s1oWH:bnfp4nl)*

**Comment by Saulis** [comment]
Review status: 7 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/visual/screens/vaadin-text-field/styling/default/chrome.png, line  at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/66#-Ki-a9JG1CgQLwDHNTzs:-Ki-f5Uir0UGvtdAgm4y:b-vvwdyd) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/9ec77b5d4bab68ad0f5bd71598d185a1ef57c983/test/visual/screens/vaadin-text-field/styling/default/chrome.png#L)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Hmm...what cropping issues?
</blockquote></details>

nevermind.. seems like the image viewer in GitHub had some issues.. solved after refreshing couple of times.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/66)*

**Comment by manolo** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/66)*

**Pull request merged**
