### PR TITLE
Improved password-field eye-button clickability

### LINKED ISSUE #113: Eye button is hard to click on mobile
Increase the touch target size in password-field default theme

### PR DESCRIPTION
**Pull request by gatanaso**
Updated password-field default theme to improve eye-button clickability.

Fixes #113

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/114)

### CODE REVIEW

**Comment by limonte** [comment]
Code is fine, but there should be slight visual changes, gemini screenshots should be updated.

**Comment by gatanaso** [comment]
@limonte Visual tests have been updated as part of this PR. Thanks for the feedback!

**Comment by YuriyVaadin** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/114#-:-Krj19dYmqzsXIMjm9bq:bg7igkv)*

**Comment by tomivirkki** [comment]
*[vaadin-password-field.html, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/114#-Krj0i6-aO1jC0_f3lOB:-Krj0i600VA4IM0Sqq-G:b-ish6bs) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c7de5c33e183d829c6089c8737b5fdb9fb00626d/vaadin-password-field.html#L25)):*
> ```HTML
>       [part="input-field"] {
>         align-items: stretch;
>         padding: 0;
> ```

I'm not too excited about modifications to the internal layouting. With normal text-field the input field has padding and part value doesn't have margin. This anomaly is bad for someone who wants to change the appearance of all vaadin text field based elements on a page.

So either change the layout to the root component (text field), or enlarge the button with other means (negative margins?). @jouni ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/114)*

**Comment by jouni** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-password-field.html, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/114#-Krj0i6-aO1jC0_f3lOB:-KrjorYRtxDcAplXabLA:bmyodik) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c7de5c33e183d829c6089c8737b5fdb9fb00626d/vaadin-password-field.html#L25)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I'm not too excited about modifications to the internal layouting. With normal text-field the input field has padding and part value doesn't have margin. This anomaly is bad for someone who wants to change the appearance of all vaadin text field based elements on a page.

So either change the layout to the root component (text field), or enlarge the button with other means (negative margins?). @jouni ?
</blockquote></details>

Yeah, I dislike this approach as well. I would rather leave fixing this issue to proper themes (as that’s the way combo box and date picker themes currently work) or then use negative margins. If we implement some fix for the password field, we should align combo box and date picker default themes with the same approach.

---

*[vaadin-password-field.html, line 43 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/114#-KrjokOAbc1oziwKl-7r:-KrjokOAbc1oziwKl-7s:b59z0qn) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c7de5c33e183d829c6089c8737b5fdb9fb00626d/vaadin-password-field.html#L43)):*
> ```HTML
>         justify-content: center;
>         align-items: center;
>         width: 30px;
> ```

Use 2em instead, so it’ll scale with the font size.

Also, I would name this part “reveal-button”.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/114)*

**Comment by gatanaso** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-password-field.html, line 43 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/114#-KrjokOAbc1oziwKl-7r:-KrkGrGtFej5_-RwFVXm:b-2dye60) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c7de5c33e183d829c6089c8737b5fdb9fb00626d/vaadin-password-field.html#L43)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Use 2em instead, so it’ll scale with the font size.

Also, I would name this part “reveal-button”.
</blockquote></details>

Yes it makes sense to use 2em instead. And I also agree that 'reveal' works better than 'toggle'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/114)*

**Comment by limonte** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-password-field.html, line 43 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/114#-KrjokOAbc1oziwKl-7r:-KsJJAX0ZrJ4mKubCytg:bh2lepn) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c7de5c33e183d829c6089c8737b5fdb9fb00626d/vaadin-password-field.html#L43)):*
> Also, I would name this part “reveal-button”.

Done in separated PR: https://github.com/vaadin/vaadin-text-field/pull/122

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/114)*

**Comment by limonte** [comment]
This PR is partly done with https://github.com/vaadin/vaadin-text-field/pull/122 and https://github.com/vaadin/vaadin-text-field/pull/123

Theming changes for the default theme will be discussed and applied in another PR.

Thanks @gatanaso for the contribution!

**Pull request closed without merging**
