### PR TITLE
Get default value from content text (fix #160)

### LINKED ISSUE #160: vaadin-text-area should take innerHTML as its initial value
Since in textarea you can setup the initial value in this way 

```
<textarea>
   any text or html content as initial value
</textarea>
```
I would expect the same syntax for vaadin-text-area

```
<vaadin-text-area>
   any text or html content as initial value
</vaadin-text-area>
```

### PR DESCRIPTION
**Pull request by ermitaval**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/172)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-text-area.html, line 159 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/172#-KzYpt1r9Xjfv6goUs90:-KzYpt1r9Xjfv6goUs91:b-6g307z) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/d1ec5457a07b8da4c7b6fc80f53963042636e3c1/vaadin-text-area.html#L159)):*
> ```HTML
>           const innerValue = this.textContent.replace(/^ *\n/, '');
>           if (!this.value && innerValue) {
>             this.value = innerValue;
> ```

could you please add a test for this new behavior?

---

*[demo/text-area-demos.html, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/172#-KzYpxuhY8hieUOaYOoF:-KzYpxui-OHy6urzC4wh:bu4w177) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/d1ec5457a07b8da4c7b6fc80f53963042636e3c1/demo/text-area-demos.html#L62)):*
> ```HTML
>       <template preserve-content>
>         <vaadin-text-area>
> As in the HTML textarea,
> ```

if changing number of whitespaces matters, this should be documented and also covered with test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/172)*

**Comment by ermitaval** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-text-area.html, line 159 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/172#-KzYpt1r9Xjfv6goUs90:-KzZ4PRv44LCrAZ7YlV5:bxrjxy) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/d1ec5457a07b8da4c7b6fc80f53963042636e3c1/vaadin-text-area.html#L159)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

could you please add a test for this new behavior?
</blockquote></details>

Added, I hope they are enough

---

*[demo/text-area-demos.html, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/172#-KzYpxuhY8hieUOaYOoF:-KzZ4RF4Up6OPwGfCZnY:b-s1uhi2) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/d1ec5457a07b8da4c7b6fc80f53963042636e3c1/demo/text-area-demos.html#L62)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

if changing number of whitespaces matters, this should be documented and also covered with test.
</blockquote></details>

Yes in the tests those spaces are checked

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/172)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/172#-:-Kzcvo77PO0hxXQBilRA:bnfp4nl)*

**Comment by web-padawan** [comment]
Closing this for now as we didn't agree on the feature, also CLA isn't signed.

Let's keep #160 open use this PR in future if we agree to implement this.

**Pull request closed without merging**
