### PR TITLE
Workaround IE11 placeholder issues

### PR DESCRIPTION
**Pull request by web-padawan**
Connected to vaadin/vaadin-date-picker#517

The link to the original [IE bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101220/).

@platosha I know you don't like flags but this time I really have no idea how to handle it better.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/203)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/203#-:-L6uK-qIycrk7aJ5OOuM:bnfp4nl)*

**Comment by platosha** [comment]
Nice!

:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/203#-:-L79-GOZ5PUlGg0Wm2OI:bd6o4lx)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/vaadin-text-field-mixin.html, line 328 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/203#-L79-N-pIGindz5Ha922:-L79-N-pIGindz5Ha923:b8q54wv) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/59c12c9b9f33f1ae22fe5e87192d5a0549c8965c/src/vaadin-text-field-mixin.html#L328)):*
> _preventNextInput

It could be a variable in the method block instead of in `this`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/203)*

**Comment by web-padawan** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-text-field-mixin.html, line 328 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/203#-L79-N-pIGindz5Ha922:-L793W1OAfsSsT0dA5pY:b-9ktmxb) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/59c12c9b9f33f1ae22fe5e87192d5a0549c8965c/src/vaadin-text-field-mixin.html#L328)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

> _preventNextInput

It could be a variable in the method block instead of in `this`
</blockquote></details>

Changed the implementation to not use flag. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/203)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-text-field/203)*

**Pull request merged**
