### PR TITLE
Fixing margins and id of the error message

### LINKED ISSUE #103: Problem with hidden error message
When the error-message is hidden it still has margins.

txt_erm

### PR DESCRIPTION
**Pull request by YuriyVaadin**
fixes #103

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/104)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104#-:-KpFOruVj8n6W1ZErexW:bnfp4nl)*

**Comment by limonte** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104)*

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104#-KpF_2EGw7M3e3Aw69Rs:-KpF_2EGw7M3e3Aw69Rt:bua8bla) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/addc45e03c43216fa469c4b6ede6be5783c2a919/vaadin-text-field.html#L55)):*
> ```HTML
>       }
> 
>       [part="error-message"][hidden] {
> ```

Why is this here? A "[hidden]" div has "display: none;" by default so this rule should have no effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104)*

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104#-KpF_2EGw7M3e3Aw69Rs:-KpJdUr0ZjuwEQCDw6GE:b5iwuxd) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/addc45e03c43216fa469c4b6ede6be5783c2a919/vaadin-text-field.html#L55)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why is this here? A "[hidden]" div has "display: none;" by default so this rule should have no effect.
</blockquote></details>

Ping @limonte, why is this rule here in the default styles? I see it's currently in master.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104#-KpF_2EGw7M3e3Aw69Rs:-KpJjmDaqMKKg-h60hkW:b44gxe3) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/addc45e03c43216fa469c4b6ede6be5783c2a919/vaadin-text-field.html#L55)):*
@tomivirkki 

> A "[hidden]" div has "display: none;" by default

Usually yes, but not for the Valo theme: https://github.com/vaadin/vaadin-themes/blob/72f81a16415ab2952f06bff0fa656d55132801e7/valo/vaadin-text-field.html#L202

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104)*

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104#-KpF_2EGw7M3e3Aw69Rs:-KpJknxcBxutdL2WW60q:b-l5dp5c) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/addc45e03c43216fa469c4b6ede6be5783c2a919/vaadin-text-field.html#L55)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

@tomivirkki 

> A "[hidden]" div has "display: none;" by default

Usually yes, but not for the Valo theme: https://github.com/vaadin/vaadin-themes/blob/72f81a16415ab2952f06bff0fa656d55132801e7/valo/vaadin-text-field.html#L202
</blockquote></details>

Then it’s Valo theme’s business. Text-field default styles should know nothing about nor should be affected by Valo theme.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104#-KpF_2EGw7M3e3Aw69Rs:-KpJl7FbxD_r5wKWWHL1:bejj35i) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/addc45e03c43216fa469c4b6ede6be5783c2a919/vaadin-text-field.html#L55)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Then it’s Valo theme’s business. Text-field default styles should know nothing about nor should be affected by Valo theme.
</blockquote></details>

True that, I'll revert this change. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104)*

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104#-KpF_2EGw7M3e3Aw69Rs:-KpJlLE1GVEsjA3gtBJa:b-giakgl) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/addc45e03c43216fa469c4b6ede6be5783c2a919/vaadin-text-field.html#L55)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

True that, I'll revert this change. Thanks!
</blockquote></details>

Additionally, the proper fix is to enforce `display:none` for the "[hidden]" element, not override a margin value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/104)*

**Pull request merged**
