### PR TITLE
Add webcomponents.org example and screenshot

### PR DESCRIPTION
**Pull request by limonte**
The next release should be beta, those changes are essential to get a green light from beta reviewers.

webcomponents.org link: https://www.webcomponents.org/preview/vaadin/vaadin-text-field/378d6a313bad405db4c791f3c4556018296d88fb

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/106)

### CODE REVIEW

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-:-KqNZbBAOjcTyxsKkWl_:bnfp4nl)*

**Comment by samiheikki** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 26 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-Kr5h4LWmLjXMzWcfYQ1:-Kr5h4LXgajj538y0-2F:b-ih0h0c) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/b715e779cbec0d540107505ea3477ceaa22e46ea/README.md#L26)):*
> ```Markdown
> ```html
> 
> <link rel="import" href="vaadin-themes/material/vaadin-text-field.html">
> ```

Using the demo in webcomponents.org doesn't allow changing material/valo theme because valo is already loaded in the custom-element-demo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106)*

**Comment by limonte** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 26 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-Kr5h4LWmLjXMzWcfYQ1:-KrfKFB_AsvpJ7Xm7C4b:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/b715e779cbec0d540107505ea3477ceaa22e46ea/README.md#L26)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Using the demo in webcomponents.org doesn't allow changing material/valo theme because valo is already loaded in the custom-element-demo.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106)*

**Comment by platosha** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 29 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-KrkN83aZw_kcf7cFpPM:-KrkN83aZw_kcf7cFpPN:b8hng5o) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/61feb5c2d2358ae8d433517014269968bd96bd8d/README.md#L29)):*
> ```Markdown
> ```
> 
> [Screenshot of vaadin-text-field](https://vaadin.com/elements/-/element/vaadin-text-field)
> ```

BTW Would be even better with retina resolution image here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106)*

**Comment by samiheikki** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 26 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-Kr5h4LWmLjXMzWcfYQ1:-Krogfc_c9kq4XgI6pI5:bnuks77) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/b715e779cbec0d540107505ea3477ceaa22e46ea/README.md#L26)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Removed.
</blockquote></details>

Can you add a comment like `expand to change a theme - Material or Valo` Now the live demo doesn't provide any indication that the theme can be changed: https://www.webcomponents.org/preview/vaadin/vaadin-text-field/61feb5c2d2358ae8d433517014269968bd96bd8d

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106)*

**Comment by limonte** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 26 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-Kr5h4LWmLjXMzWcfYQ1:-KsdfhTvb6oCrf3VNFTi:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/b715e779cbec0d540107505ea3477ceaa22e46ea/README.md#L26)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Can you add a comment like `expand to change a theme - Material or Valo` Now the live demo doesn't provide any indication that the theme can be changed: https://www.webcomponents.org/preview/vaadin/vaadin-text-field/61feb5c2d2358ae8d433517014269968bd96bd8d
</blockquote></details>

Done.

---

*[README.md, line 29 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-KrkN83aZw_kcf7cFpPM:-KsdfkCgRMiY8JXbCu-w:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/61feb5c2d2358ae8d433517014269968bd96bd8d/README.md#L29)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW Would be even better with retina resolution image here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-:-KshY8ct0sYolFckSx7t:bnfp4nl)*

**Comment by tomivirkki** [comment]
Vaadin Themes hasn't been released so we can't promote using them here in a stable component's readme. It's not even set in stone that the import will look like that. And why have this change for `<vaadin-text-field>` only? What about the other elements?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-:-KsnYdC1N6-DmHyivryr:b7qhrp6)*

**Comment by manolo** [comment]
Well, this for a beta of vaadin-text-field, then it's not so bad to have the theming dependency in a beta, though we need to take care of not releasing until themes is stable.

But in the other hand, we would like to release stable version of text-field, hence we should avoid the dependency.

So the second reason is strongest to me, so  I will retain this branch un-merged .

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-:-Kso1vnAJeochEH4SpkX:b-195ft4)*

**Comment by tomivirkki** [comment]
Text field is already [stable](https://github.com/vaadin/vaadin-text-field/releases/tag/v1.0.0). And theming dependency is not beta, not even an alpha yet. Readme shown in the repo always shows master by default so yeah, we can't merge this until Valo beta

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-:-Kso3Gftz7dH7OeBbjK4:bnyzgy9)*

**Comment by limonte** [comment]
@jouni what do you think about this PR? Do we have any est on Valo beta?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-:-KsoGchiRGtqJ4nXsKtT:b-468lap)*

**Comment by jouni** [comment]
@limonte my guesstimate for vaadin-themes 1.0 beta somewhere around November/December

**Comment by platosha** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-:-KtBarMJvAHHI3zeU-FI:bnfp4nl)*

**Comment by platosha** [comment]
Needs rebase. Feel free to merge when rebased. :thumbsup: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-:-KtBavc_NNA2L3Vn90sb:byh2et3)*

**Comment by platosha** [comment]
Oh, sorry to confuse. Mind that Valo is not in a public release yet, so can’t merge.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/106#-:-KtBbvpx6_fbuZyzLWk6:bypy9gq)*

**Comment by jouni** [comment]
> Mind that Valo is not in a public release yet, so can’t merge.

It’s public, but not stable. I’m okay if you want to display it in the webcomponents.org demo. I don’t see us making any big changes to it anymore, at least any breaking changes.

**Comment by limonte** [comment]
> I don’t see us making any big changes to it anymore, at least any breaking changes.

@jouni This one looks like the upcoming breaking change: https://github.com/vaadin/vaadin-themes/issues/48#issuecomment-326724162

**Comment by limonte** [comment]
webcomponents.org example fixed in https://github.com/vaadin/vaadin-text-field/commit/faf2be1dec11c3b7b6e74e52a716b650c08956d6

Screenshots will be handled after Valo and Material stable release.

**Pull request closed without merging**
