### PR TITLE
Implement focus-ring

### PR DESCRIPTION
**Pull request by limonte**
The A11ycasts lesson showing the diff between focus and focus-ring: https://youtu.be/ilj2P5-5CjI 

Connected to https://github.com/vaadin/vaadin-button/issues/4

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/52)

### CODE REVIEW

**Comment by Saulis** [comment]
As discussed live, we want to have both the `focused` and `focus-ring`properties

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-:-KgwnjSCI9LpBnbC2W82:b-twfntr)*

**Comment by tomivirkki** [comment]
No tests in this feature PR?

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-Kh2a77lnWyPBWOzYZLe:-Kh2a77lnWyPBWOzYZLf:b-spjaih) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/388bdcfa7658d560076ae7837dac3d9089ff8ba5/vaadin-control-state-mixin.html#L34)):*
> ```HTML
>         'focusRing': {
>           type: Boolean,
>           notify: true,
> ```

Not sure if this needs to notify. `focused` is already notified so I don't see a use case for this extra event that occurs only on keyboard focus.

---

*[vaadin-control-state-mixin.html, line 91 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-Kh2_JNsMhSF2hWLHjHR:-Kh2_JNsMhSF2hWLHjHS:b-efjvby) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/388bdcfa7658d560076ae7837dac3d9089ff8ba5/vaadin-control-state-mixin.html#L91)):*
> ```HTML
>       }
> 
>       document.body.addEventListener('keydown', e => {
> ```

Since you're adding the listeners to `<body>` (instead of `this`)  they need to be cleaned also. Good pattern is to add them on `attached` and remove the on `detached`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-:-Kh2aru6oEAWc7op8aPY:bm8el83)*

**Comment by Saulis** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[vaadin-control-state-mixin.html, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-Kh2a77lnWyPBWOzYZLe:-KhMl3VupUj9-_froPtx:b2ub3sf) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/388bdcfa7658d560076ae7837dac3d9089ff8ba5/vaadin-control-state-mixin.html#L34)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Not sure if this needs to notify. `focused` is already notified so I don't see a use case for this extra event that occurs only on keyboard focus.
</blockquote></details>

I'd say yes – for all properties that can have their value changed internally, there should be `notify: true`. What this could also use is `readOnly: true`.

---

*[test/control-state.html, line 75 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhMmXjBqei1zOb46KUd:-KhMmXjBqei1zOb46KUe:b-8kzwal) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/ebf70276015c64f924af2e5b7b56baf817cfc68f/test/control-state.html#L75)):*
> ```HTML
>             focusElement.focus();
>             expect(customElement.focused).to.be.true;
>             expect(customElement.focusRing).to.be.true;
> ```

`focusRing` should be false since tab isn't pressed?

Please add new tests that test the `focus` and `focusRing` in different states when `_tabPressed` is `true` and `false`.

Also, separate tests should be added to verify that key events set `_tabPressed` correctly.

---

*[test/control-state.html, line 88 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhMmIzgwiSzCXREV6dq:-KhMmIzhfn4o1ThHi18M:b1s2cw1) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/ebf70276015c64f924af2e5b7b56baf817cfc68f/test/control-state.html#L88)):*
> ```HTML
>             customElement.click();
>             expect(customElement.focused).to.be.true;
>             expect(customElement.focusRing).to.be.true;
> ```

`focusRing` should be false on click

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by tomivirkki** [comment]
*[vaadin-control-state-mixin.html, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-Kh2a77lnWyPBWOzYZLe:-KhMoNNf3fJljufV_Ojl:b8rfk04) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/388bdcfa7658d560076ae7837dac3d9089ff8ba5/vaadin-control-state-mixin.html#L34)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I'd say yes – for all properties that can have their value changed internally, there should be `notify: true`. What this could also use is `readOnly: true`.
</blockquote></details>

Actually, is there a reason for this to be a property other than getting it to reflect to an attribute? If not, then a simple `setAttribute` in `_focusedChanged` would save us from expanding the public interface with an unnecessary read-only property and an event.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by Saulis** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[vaadin-control-state-mixin.html, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-Kh2a77lnWyPBWOzYZLe:-KhQdWLT5Vwd36xojyWE:b-505ih3) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/388bdcfa7658d560076ae7837dac3d9089ff8ba5/vaadin-control-state-mixin.html#L34)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Actually, is there a reason for this to be a property other than getting it to reflect to an attribute? If not, then a simple `setAttribute` in `_focusedChanged` would save us from expanding the public interface with an unnecessary read-only property and an event.
</blockquote></details>

Yeah good point, this is only needed for styling so we might as well go with a plain attribute. :+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by tomivirkki** [comment]
*[vaadin-control-state-mixin.html, line 91 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRKYbEt0SCE6qACXjZ:-KhRKYbEt0SCE6qACXj_:b-gn3el4) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/124cecf89774bb538cc085d42081237e7cc13463/vaadin-control-state-mixin.html#L91)):*
> ```HTML
>       super.disconnectedCallback();
> 
>       document.body.removeEventListener('keydown', this._bodyKeydownListener.bind(this), true);
> ```

The listener instance you remove here must be the same one that's added in `connectedCallback`. The instance can be created for example in the constructor. Here's an example: https://github.com/vaadin/vaadin-combo-box/blob/745fa994a545521c42f76bf890a07923ddaf7b99/vaadin-overlay-behavior.html#L40

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by limonte** [comment]
Done

---

Review status: 0 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-Kh2a77lnWyPBWOzYZLe:-KhRj7Ki2ni-GF_Is5kf:b-xto6p2) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/388bdcfa7658d560076ae7837dac3d9089ff8ba5/vaadin-control-state-mixin.html#L34)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Yeah good point, this is only needed for styling so we might as well go with a plain attribute. :+1:
</blockquote></details>

Done, thanks a lot to both of you for help! I owe you those weird black candies :D 

---

*[vaadin-control-state-mixin.html, line 91 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-Kh2_JNsMhSF2hWLHjHR:-KhRjTFlzjJts6BCNoZs:b-xiw2bp) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/388bdcfa7658d560076ae7837dac3d9089ff8ba5/vaadin-control-state-mixin.html#L91)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Since you're adding the listeners to `<body>` (instead of `this`)  they need to be cleaned also. Good pattern is to add them on `attached` and remove the on `detached`
</blockquote></details>

Nice catch, done.

---

*[vaadin-control-state-mixin.html, line 91 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRKYbEt0SCE6qACXjZ:-KhRjX9SvdQxdiKA6Lib:b8a8f7g) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/124cecf89774bb538cc085d42081237e7cc13463/vaadin-control-state-mixin.html#L91)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The listener instance you remove here must be the same one that's added in `connectedCallback`. The instance can be created for example in the constructor. Here's an example: https://github.com/vaadin/vaadin-combo-box/blob/745fa994a545521c42f76bf890a07923ddaf7b99/vaadin-overlay-behavior.html#L40
</blockquote></details>

You're right, done.

---

*[test/control-state.html, line 75 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhMmXjBqei1zOb46KUd:-KhRjbGQbpua2DFTJ1xk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/ebf70276015c64f924af2e5b7b56baf817cfc68f/test/control-state.html#L75)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

`focusRing` should be false since tab isn't pressed?

Please add new tests that test the `focus` and `focusRing` in different states when `_tabPressed` is `true` and `false`.

Also, separate tests should be added to verify that key events set `_tabPressed` correctly.
</blockquote></details>

Done.

---

*[test/control-state.html, line 88 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhMmIzgwiSzCXREV6dq:-KhRjdgAaNTeU1jXaElh:bsyq227) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/ebf70276015c64f924af2e5b7b56baf817cfc68f/test/control-state.html#L88)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

`focusRing` should be false on click
</blockquote></details>

Not relevant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-:-Kh1FzEhZnMxyB6XGzUS:bb6un1j)*

**Comment by manolo** [comment]
Reviewed 6 of 16 files at r3, 8 of 15 files at r4, 5 of 8 files at r5.
Review status: 16 of 20 files reviewed at latest revision, 9 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 8 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRo-nXP-sLl54Wkewi:-KhRo-nXP-sLl54Wkewj:b-u2hrar) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/vaadin-control-state-mixin.html#L8)):*
> ```HTML
>   Vaadin.ControlStateMixin = subclass => class VaadinControlStateMixin extends subclass {
>     static get properties() {
>       var properties = {
> ```

Is there a reason for renaming the var. Actually I named it first properties, but ended out with a different name in order to avoid confusion with the object's static properties variable.

---

*[test/control-state.html, line 91 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRspnw7cLrFM0wkFTS:-KhRspnxIMvJvQKeRAYt:bwgbjtw) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/test/control-state.html#L91)):*
> ```HTML
> 
>       describe('_tabPressed', function() {
>         it('should set and unset this._tabPressed when press TAB', function() {
> ```

I don't think `this.` adds some value to the description, even it could be a bit confusing, just `_tabPressed` is meaningful 

---

*[test/visual/common.html, line 8 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRtmiH4ObscfMjl9ln:-KhRtmiH4ObscfMjl9lo:b-sxt45) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/test/visual/common.html#L8)):*
> ```HTML
>   HTMLImports.whenReady(function() {
>     var hiddenCaretInputs = document.querySelectorAll('.hidden-caret');
>     for (var i = 0; i < hiddenCaretInputs.length; i++) {
> ```

don't JS coders prefer the `[].forEach.call(` way? ;-)  not blocker

---

*[test/visual/test.js, line 7 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRuA1BA6k68LFKBD95:-KhRuA1BA6k68LFKBD96:bx2guta) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/test/visual/test.js#L7)):*
> ```JavaScript
>     actions.waitForJSCondition(function(window) {
>       return window.webComponentsAreReady;
>     }, 60000);
> ```

do we need one minute here, I see  a very long timer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by limonte** [comment]
Review status: 14 of 20 files reviewed at latest revision, 9 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 8 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRo-nXP-sLl54Wkewi:-KhRv_TPX0YRA-IWzdBo:b-pjf29m) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/vaadin-control-state-mixin.html#L8)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Is there a reason for renaming the var. Actually I named it first properties, but ended out with a different name in order to avoid confusion with the object's static properties variable.
</blockquote></details>

`cfg` is the bad var name in this case, since this array isn't related to any "configuration". I don't see how the local variable `prorerties` can cause any confusion. 

---

*[test/control-state.html, line 91 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRspnw7cLrFM0wkFTS:-KhRwGEAH5d-6bAbo_FR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/test/control-state.html#L91)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I don't think `this.` adds some value to the description, even it could be a bit confusing, just `_tabPressed` is meaningful 
</blockquote></details>

Done.

---

*[test/visual/common.html, line 8 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRtmiH4ObscfMjl9ln:-KhRwDvWeQjrHimMR231:bhmhk5s) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/test/visual/common.html#L8)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

don't JS coders prefer the `[].forEach.call(` way? ;-)  not blocker
</blockquote></details>

Nice catch! Done.

---

*[test/visual/test.js, line 7 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRuA1BA6k68LFKBD95:-KhRw76d_0xCAFdJ4AWL:b607o2v) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/test/visual/test.js#L7)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

do we need one minute here, I see  a very long timer
</blockquote></details>

copy-pasted from https://github.com/vaadin/vaadin-form-layout/pull/13 which was reviewed by you ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by limonte** [comment]
Review status: 14 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

*[test/visual/test.js, line 7 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRuA1BA6k68LFKBD95:-KhS5zzDdYzeoW3S1-uh:b-cgalmm) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/test/visual/test.js#L7)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

copy-pasted from https://github.com/vaadin/vaadin-form-layout/pull/13 which was reviewed by you ;)
</blockquote></details>

I reverted this to the simple timeout, event-handler was flaky for some unknown reason 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by tomivirkki** [comment]
:lgtm: 

---

Reviewed 6 of 16 files at r3, 9 of 15 files at r4, 5 of 8 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-:-KhS743HsqvcR59mnvQL:bg7igkv)*

**Comment by limonte** [comment]
Review status: 16 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

*[test/visual/test.js, line 7 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRuA1BA6k68LFKBD95:-KhSBIqv7Lvr2XYXxN4H:b-225iqp) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/test/visual/test.js#L7)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I reverted this to the simple timeout, event-handler was flaky for some unknown reason 
</blockquote></details>

The weird flakiness is happening here. For now fixed by waiting for `WebComponentsReady` event and then `3s` more. I have no idea on reason for this :/ 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by tomivirkki** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 8 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRo-nXP-sLl54Wkewi:-KhWI-WXoT2m-5uLAjqH:b4sjirr) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/vaadin-control-state-mixin.html#L8)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`cfg` is the bad var name in this case, since this array isn't related to any "configuration". I don't see how the local variable `prorerties` can cause any confusion. 
</blockquote></details>

+1 for `properties` 

---

*[test/control-state.html, line 75 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhMmXjBqei1zOb46KUd:-KhWHhj6-SiIAy6KhVYd:b-dsph1z) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/ebf70276015c64f924af2e5b7b56baf817cfc68f/test/control-state.html#L75)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still hoping to see a tests to verify `focus-ring` attribute is set only when `_tabPressed` is `true` (and removed on blur)

---

*[test/performance/config.json, line 2 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhWHRYPHgmRXf6hC7de:-KhWHRYPHgmRXf6hC7df:bpdtp2h) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/776c90eed7b72241ee453197efb8ffbe2267a81a/test/performance/config.json#L2)):*
> ```JSON
> [
>   {"name": "index.html", "threshold": 0.7}
> ```

Has the performance dropped?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by limonte** [comment]
Review status: 15 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/control-state.html, line 75 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhMmXjBqei1zOb46KUd:-KhWPrUVPaUR1x981UDI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/ebf70276015c64f924af2e5b7b56baf817cfc68f/test/control-state.html#L75)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Still hoping to see a tests to verify `focus-ring` attribute is set only when `_tabPressed` is `true` (and removed on blur)
</blockquote></details>

Done.

---

*[test/performance/config.json, line 2 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhWHRYPHgmRXf6hC7de:-KhWKUwc_hCBWHC8w0mq:b-4d1ifo) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/776c90eed7b72241ee453197efb8ffbe2267a81a/test/performance/config.json#L2)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Has the performance dropped?
</blockquote></details>

lighthouse tests were unstable as fuck yesterday :/ I run tests around 20 times and sometimes build was red. The performance was from 0.6 to 0.75.

Fortunately, I noticed that there's a new `lighthouse` release and after update to `~1.6.0` performance test works like a charm :) So I increased the threshold to 0.85 and it looks quite stable now. Yay!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by manolo** [comment]
Review status: 15 of 20 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[vaadin-control-state-mixin.html, line 8 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRo-nXP-sLl54Wkewi:-KhWdhjwu4PLj4pnitRU:b-cxvgbl) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/vaadin-control-state-mixin.html#L8)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

+1 for `properties` 
</blockquote></details>

it's a matter of taste. I do prefer not having the same name in a private context than the public one. Not blocker though

---

*[test/visual/common.html, line 10 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhWeofPuTKNYuUU_1sn:-KhWeofPuTKNYuUU_1so:bmneikn) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/544750527b6f0b702d5f43cb07d9b540908b1698/test/visual/common.html#L10)):*
> ```HTML
>   HTMLImports.whenReady(function() {
>     var hiddenCaretInputs = document.querySelectorAll('.hidden-caret');
>     hiddenCaretInputs.forEach(function(input) {
> ```

hiddenCaretsInput is a nodeList not an array, so it would fail in other browsers or if Polymer does not handles the query, that the reason I recommended the usage of `call` in the array

---

*[test/visual/test.js, line 7 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRuA1BA6k68LFKBD95:-KhWfASJrhQNeFrTlPhE:b-a5smve) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/test/visual/test.js#L7)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

The weird flakiness is happening here. For now fixed by waiting for `WebComponentsReady` event and then `3s` more. I have no idea on reason for this :/ 
</blockquote></details>

5 seconds looks better, I dont want to have one minute running the test if the component is never ready

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by manolo** [comment]
Review status: 15 of 20 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[test/control-state.html, line 112 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhWiE3nsm5M1RzQ8pCO:-KhWiE3oKigB9A71IltC:b-wquz4h) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/544750527b6f0b702d5f43cb07d9b540908b1698/test/control-state.html#L112)):*
> ```HTML
>         });
> 
>         it('should set the focus-ring attribute when _tabPressed is true', function() {
> ```

Could you also cover the shift-tab case ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by limonte** [comment]
Review status: 15 of 20 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[test/control-state.html, line 112 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhWiE3nsm5M1RzQ8pCO:-KhWmlA2Wxcy-niSEu6E:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/544750527b6f0b702d5f43cb07d9b540908b1698/test/control-state.html#L112)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Could you also cover the shift-tab case ? 
</blockquote></details>

done

---

*[test/visual/common.html, line 10 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhWeofPuTKNYuUU_1sn:-KhWmi_zN09DwzBEaDmE:bdctd94) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/544750527b6f0b702d5f43cb07d9b540908b1698/test/visual/common.html#L10)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

hiddenCaretsInput is a nodeList not an array, so it would fail in other browsers or if Polymer does not handles the query, that the reason I recommended the usage of `call` in the array
</blockquote></details>

done, thx!

---

*[test/visual/test.js, line 7 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-KhRuA1BA6k68LFKBD95:-KhWmjlXId2tSAvLLS8M:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/8d5b5621785dbd113d3f3046aaa7eb499a0da330/test/visual/test.js#L7)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

5 seconds looks better, I dont want to have one minute running the test if the component is never ready
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52)*

**Comment by Saulis** [comment]
:lgtm_strong: 

---

Reviewed 6 of 16 files at r3, 7 of 15 files at r4, 1 of 8 files at r5, 2 of 4 files at r7, 2 of 5 files at r8, 5 of 5 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/52#-:-KhX96DxIwoNfctYCC9_:b-uwkowd)*

**Pull request merged**
