### PR TITLE
Custom Validators

### PR DESCRIPTION
**Pull request by manolo**
Connected to #28

I will add tests after discussing the implementation

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/50)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 248 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgnd0xMPVOU3TaQBgGe:-Kgnd0xMPVOU3TaQBgGf:b-rt6gci) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/7d43604d533875c20ec9915aa4327e10b58cfddb/vaadin-text-field.html#L248)):*
> ```HTML
>       }
> 
>       _valueChanged(value) {
> ```

There shouldn't be any need to change this file in the PR. The demo's should use the bare bone version of text field, not material.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50)*

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 248 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgnd0xMPVOU3TaQBgGe:-Kgndrchl8vatXm0VC-3:btrp5eq) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/7d43604d533875c20ec9915aa4327e10b58cfddb/vaadin-text-field.html#L248)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

There shouldn't be any need to change this file in the PR. The demo's should use the bare bone version of text field, not material.
</blockquote></details>

default styling does not mark invalid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50)*

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 248 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgnd0xMPVOU3TaQBgGe:-KgndzeQQodTGlhzaGl4:b-peic30) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/7d43604d533875c20ec9915aa4327e10b58cfddb/vaadin-text-field.html#L248)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

default styling does not mark invalid
</blockquote></details>

and validate should be called always, not reason to only be called when it is invalid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50)*

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 248 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgnd0xMPVOU3TaQBgGe:-KgneEH3qh_hAz5pLFfD:bfub8kg) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/7d43604d533875c20ec9915aa4327e10b58cfddb/vaadin-text-field.html#L248)):*
> default styling does not mark invalid

Then you can add a style for it in the demo. We _need_ the bare bone versions of the examples since we're going to remove the material style from the repo really soon.

> and validate should be called always, not reason to only be called when it is invalid.

If it's needed by this PR then ok. Please add a test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50)*

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-text-field.html, line 248 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgnd0xMPVOU3TaQBgGe:-Kgng4072gMBD-E-z91h:bbd068w) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/7d43604d533875c20ec9915aa4327e10b58cfddb/vaadin-text-field.html#L248)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

> default styling does not mark invalid

Then you can add a style for it in the demo. We _need_ the bare bone versions of the examples since we're going to remove the material style from the repo really soon.

> and validate should be called always, not reason to only be called when it is invalid.

If it's needed by this PR then ok. Please add a test.
</blockquote></details>

The removal of MD is later to this PR, so in this task could be removed this or changed 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50)*

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 248 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgnd0xMPVOU3TaQBgGe:-KgnhKLsSnw5oCz4ffJe:bu26e5w) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/7d43604d533875c20ec9915aa4327e10b58cfddb/vaadin-text-field.html#L248)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

The removal of MD is later to this PR, so in this task could be removed this or changed 
</blockquote></details>

Sure, but there’s still a dedicated demo page called “material design theme” for MD. Rest of the demos (just like “basic examples”) should focus on demonstrating text-field features on top of the raw version.

Even if we had decided to keep the MD module in this repo, other than the MD demo should not be MD.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50)*

**Comment by Saulis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[vaadin-text-field.html, line 248 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgnd0xMPVOU3TaQBgGe:-Kgno22Bk-bNsLw45bwV:b-hksnad) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/7d43604d533875c20ec9915aa4327e10b58cfddb/vaadin-text-field.html#L248)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Sure, but there’s still a dedicated demo page called “material design theme” for MD. Rest of the demos (just like “basic examples”) should focus on demonstrating text-field features on top of the raw version.

Even if we had decided to keep the MD module in this repo, other than the MD demo should not be MD.
</blockquote></details>

The reason why `validate()` is called only when `invalid` is to clear the invalid state. Otherwise, `validate()` is called only on demand. We can discuss if this behavior is correct or not, but let's do that in a separate issue.

---

*[vaadin-text-field.html, line 253 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgnia9vT7_EBSKWapaq:-Kgnia9vT7_EBSKWapar:b-at82ng) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c402c329d86d2f7ca2c4b2c6e686b61099540f35/vaadin-text-field.html#L253)):*
> ```HTML
>       }
> 
>       _onBlur() {
> ```

This isn't called from anywhere.

---

*[vaadin-text-field.html, line 260 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-KgnoRs7N1N0gxNh1f52:-KgnoRs7N1N0gxNh1f53:b-492zmf) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c402c329d86d2f7ca2c4b2c6e686b61099540f35/vaadin-text-field.html#L260)):*
> ```HTML
>        * Returns true if `value` is valid.
>        * `<iron-form>` uses this to check the validity or all its elements.
>        * In the case you use an asynchronous validator, you might set the
> ```

This is an implementation detail and doesn't make sense when reading the API documentation without seeing the implementation – rather say something like "Also sets the `invalid` state.`

---

*[vaadin-text-field.html, line 278 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-KgniOY8CMasLnf845Ai:-KgniOY8CMasLnf845Aj:b-lfkna7) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c402c329d86d2f7ca2c4b2c6e686b61099540f35/vaadin-text-field.html#L278)):*
> ```HTML
>       ready() {
>         super.ready();
>         this.classList.add('vaadin-text-field');
> ```

What is this class for?

---

*[demo/validators.html, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgnhm3E69NOiGIk-Sys:-Kgnhm3E69NOiGIk-Syt:byb8ijk) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c402c329d86d2f7ca2c4b2c6e686b61099540f35/demo/validators.html#L24)):*
> ```HTML
> 
>     <p>Extend <code>VaadinTextFieldElement</code> to create your own custom element,
>       then override the <code>validate()</code> method to validate user's input</p>
> ```

`checkValidity()`

---

*[demo/validators.html, line 57 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgni5gSZvVpijL6sAQY:-Kgni5gSZvVpijL6sAQZ:b-jduoit) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c402c329d86d2f7ca2c4b2c6e686b61099540f35/demo/validators.html#L57)):*
> ```HTML
>     </demo-snippet>
> 
>     <h3>Asynchronous Custom Validator</h3>
> ```

Can you modify this example to be really asynchronous so that user can see that the validation happens after a delay? Also, you can't see which values are allowed by looking at the demo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/validators.html, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgnhm3E69NOiGIk-Sys:-KgrLjZFZ254CdQrbdA_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c402c329d86d2f7ca2c4b2c6e686b61099540f35/demo/validators.html#L24)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

`checkValidity()`
</blockquote></details>

Done.

---

*[demo/validators.html, line 57 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgni5gSZvVpijL6sAQY:-KgrLlck8MZdnjjm8l5W:b7v4dxq) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c402c329d86d2f7ca2c4b2c6e686b61099540f35/demo/validators.html#L57)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Can you modify this example to be really asynchronous so that user can see that the validation happens after a delay? Also, you can't see which values are allowed by looking at the demo.
</blockquote></details>

It was really async since using an ajax request, in production the delay should be more noticeable, and the developer could inspect devtools to see that XHR really happens.
Anyways, replaced by a mocked iron-ajax implementation like we have in other elements, with a delay of 1000ms.

---

*[vaadin-text-field.html, line 248 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgnd0xMPVOU3TaQBgGe:-KgrNAtegVviyts-7GAU:b-qex5pe) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/7d43604d533875c20ec9915aa4327e10b58cfddb/vaadin-text-field.html#L248)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

The reason why `validate()` is called only when `invalid` is to clear the invalid state. Otherwise, `validate()` is called only on demand. We can discuss if this behavior is correct or not, but let's do that in a separate issue.
</blockquote></details>

Actually it was there in order not to mark as invalid in the very first time the component was used. I mean when the component is rendered the first time, Jouni didn't want the status be red until the user writes the first time and blur.

But after seeing it in action it makes not sense that in each value change (each single letter typed by the user) the flag changes when it's invalid but not at the contrary, causing a bad UX (see http://g.recordit.co/lg3ipGlZGo.gif). If we consider to call validate in `value-changed` it should be called always and not to depend on the previous status.

I thought this minor issue manifested in this story, could be fixed directly without the bureaucracy of a new Issue, discussion and PR. But let's do in the long way.

---

*[vaadin-text-field.html, line 253 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-Kgnia9vT7_EBSKWapaq:-KgrMI7a4I6j4ofsqULv:b-amfnml) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c402c329d86d2f7ca2c4b2c6e686b61099540f35/vaadin-text-field.html#L253)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This isn't called from anywhere.
</blockquote></details>

Was left here after the merging. Done

---

*[vaadin-text-field.html, line 260 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-KgnoRs7N1N0gxNh1f52:-KgrMP0PTDb6GS6iFekC:b-5mutsj) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c402c329d86d2f7ca2c4b2c6e686b61099540f35/vaadin-text-field.html#L260)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This is an implementation detail and doesn't make sense when reading the API documentation without seeing the implementation – rather say something like "Also sets the `invalid` state.`
</blockquote></details>

In the first implementation, validate() was not changing the invalid flag, this had the same responsibility than the current checkValidity. So the API should notice the point. Anyways replaced. 

---

*[vaadin-text-field.html, line 278 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-KgniOY8CMasLnf845Ai:-KgrMiEQC0CQzf7LK-0m:bs6gpy) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/c402c329d86d2f7ca2c4b2c6e686b61099540f35/vaadin-text-field.html#L278)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

What is this class for?
</blockquote></details>

You cannot apply our vaadin material design theme otherwise because it's using selectors based on the tag-name which changes when extending.
Since assumptions about how the theming will be has changed from the time I started this PR, this can be fixed in a separated issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50)*

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[demo/validators.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-KgrdARRdN9jcYONul8p:-KgrdARSjJZ4ol-aa5Ut:b7qs9as) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/aca90af08eaaf738c6da833ba1b972e04cdd3f01/demo/validators.html#L12)):*
> ```HTML
>   <script src='../../webcomponentsjs/webcomponents-lite.js'></script>
>   <link rel='import' href='common.html'>
>   <link rel='import' href='material-vaadin-text-field.html'>
> ```

Unnecessary import

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[demo/validators.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-KgrdARRdN9jcYONul8p:-KgrmLzn4ahKDiCpy84P:b-smyqex) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/aca90af08eaaf738c6da833ba1b972e04cdd3f01/demo/validators.html#L12)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Unnecessary import
</blockquote></details>

Ups, forgot to remove. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r1, 1 of 7 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/50#-:-KgsZqTHS5CjPx9NMTvD:bnfp4nl)*

**Pull request merged**
