### PR TITLE
Bind name to the native input element

### PR DESCRIPTION
**Pull request by limonte**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/95)

### CODE REVIEW

**Comment by manolo** [comment]
This change is small enough to be in one commit. 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 116 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/95#-KlImfBa35JWmMuEGOKc:-KlImfBa35JWmMuEGOKd:b-19uo88) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/e3b1df2882594dd39e5d9e5e9a0b0df7a631fa85/vaadin-text-field.html#L116)):*
> ```HTML
>           maxlength$="[[maxlength]]"
>           minlength$="[[minlength]]"
>           name="[[name]]"
> ```

This was originally bound in the initial component, for some reason this was removed.
https://github.com/vaadin/vaadin-text-field/pull/1/files#diff-fc45d09e1dde251e9b6395613968686bR54

We need to know that reason befor adding this back. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/95#-:-KlImKyroLdUFdWeZBOY:bgj7c6q)*

**Comment by limonte** [comment]
Matter of taste. I prefer [commit early, commit-often](http://www.databasically.com/2011/03/14/git-commit-early-commit-often/).

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 116 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/95#-KlImfBa35JWmMuEGOKc:-KlIptD7BqNVlvC1RlCL:b-qmgo5g) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/e3b1df2882594dd39e5d9e5e9a0b0df7a631fa85/vaadin-text-field.html#L116)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This was originally bound in the initial component, for some reason this was removed.
https://github.com/vaadin/vaadin-text-field/pull/1/files#diff-fc45d09e1dde251e9b6395613968686bR54

We need to know that reason befor adding this back. 
</blockquote></details>

Good catch, https://github.com/vaadin/vaadin-text-field/pull/91

@tomivirkki what was the reason of dropping name binding?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/95#-:-KlIocn_PgvBjSa33NCk:b-t382no)*

**Comment by tomivirkki** [comment]
*[vaadin-text-field.html, line 116 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/95#-KlImfBa35JWmMuEGOKc:-KlIxt5R-9rq0bI7j_ML:b-ryh4ml) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/e3b1df2882594dd39e5d9e5e9a0b0df7a631fa85/vaadin-text-field.html#L116)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Good catch, https://github.com/vaadin/vaadin-text-field/pull/91

@tomivirkki what was the reason of dropping name binding?
</blockquote></details>

Is there some rationale for have this binding? Native forms can’t at least utilize it trough shadow root. And naturally we don’t want to have a feature that only works with shady DOM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/95)*

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 116 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/95#-KlImfBa35JWmMuEGOKc:-KlJ-S4Dm8b-on4rBlDd:b-dxcbts) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/e3b1df2882594dd39e5d9e5e9a0b0df7a631fa85/vaadin-text-field.html#L116)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is there some rationale for have this binding? Native forms can’t at least utilize it trough shadow root. And naturally we don’t want to have a feature that only works with shady DOM.
</blockquote></details>

Makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/95)*

**Pull request closed without merging**
