### PR TITLE
Include a static getter for the element version

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/168)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/168#-KyyWKXVtJBiQJOef7zs:-KyyWKXVtJBiQJOef7zt:bied3xx) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/4f5a52dc2a5e36eea8df401b279dba61140e46fa/.travis.yml#L19)):*
> ```YAML
> 
> before_script:
>   - gulp lint version:check version:check
> ```

nit: duplicate, please remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/168)*

**Comment by Artur-** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 19 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/168#-KyyWKXVtJBiQJOef7zs:-KyydLAmY6P23hf-2Cre:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/4f5a52dc2a5e36eea8df401b279dba61140e46fa/.travis.yml#L19)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: duplicate, please remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/168)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/168#-:-Kyyw8neZDTg7NGRe1zs:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm_strong: 

---

Reviewed 4 of 7 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/168#-:-Kyz7GLFJFHjmXDEZK1M:b-uwkowd)*

**Pull request merged**
