### PR TITLE
Prefix and suffix feature

### LINKED ISSUE #25: Prefix and Suffix
Use Cases to cover:
- allow adding icons/buttons inside the focusable area (think of combo-box)
- consider disabling "floating label" when prefix is defined

### PR DESCRIPTION
**Pull request by tomivirkki**
Closes #25

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/51)

### CODE REVIEW

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/51#-:-Kgn_SnKXwcvXe6ZdrVt:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/51#-:-KgncgVQhz9kIH7oMYl3:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/51#-:-KgnfkJ--GTcklMkUI6K:bnfp4nl)*

**Comment by jouni** [comment]
Nice, you made it work with floating labels as well 👍 

But why the use of id’s in the template elements? We aren’t even using the Polymer convenience accessor for those (`this.$`), and it just pollutes the DOM with multiple same id’s in polyfilled browsers. I think it would have been future-proof to use the `part="suffix"` syntax already, as we need to change to that anyway before releasing the first version.

**Comment by jouni** [comment]
Using `part` of course means we need to decide which parts to actually expose, so it was probably quicker to implement this way.

**Comment by tomivirkki** [comment]
We use id’s pretty much overall in templates to mark unique elements. There were some in this template also before this ticket and those of the new ones are mostly derived from `<paper-input-container>`. Didn’t consider switching to using the part markers as part of this specific ticket. But sure it should be done before 1.0.

**Comment by jouni** [comment]
Sure, no problem :) I’ve just always wondered this pattern, as I feel the id’s are so “heavy-weight” because of their CSS specificity and the fact that you should only have unique id’s in the DOM (we might be breaking someone’s app if they happen use the same exact id for their app specific element, right?).

**Pull request merged**
