### PR TITLE
Fix Firefox gemini tests

### PR DESCRIPTION
**Pull request by limonte**
The same issue as it was in form-layout: https://github.com/vaadin/vaadin-form-layout/blob/master/test/visual/test.js#L18-L23

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/72)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/visual/test.js, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/72#-KinG-9249grUH-1Et8k:-KinG-9249grUH-1Et8l:b-pgx2ku) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/e228a575925b03ec8ceee7da2033b16ad6033a51/test/visual/test.js#L1)):*
> ```JavaScript
> gemini.suite('vaadin-text-field', function(rootSuite) {
> ```

Maybe specify before and after to the `rootSuite`?

```javascript
rootSuite
  .before(wait)
  .after(goToAboutBlank)
```

No need to repeat callbacks in every test then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/72)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/visual/test.js, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/72#-KinG-9249grUH-1Et8k:-KinPKikvC9gtWnnTt7C:b-igq8zi) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/e228a575925b03ec8ceee7da2033b16ad6033a51/test/visual/test.js#L1)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Maybe specify before and after to the `rootSuite`?

```javascript
rootSuite
  .before(wait)
  .after(goToAboutBlank)
```

No need to repeat callbacks in every test then.
</blockquote></details>

Much better now, thanks! I will apply the same change to the skeleton and other components.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/72)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/visual/test.js, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/72#-KinG-9249grUH-1Et8k:-KinS1MdFiugaEDYqeiz:b-gvsl1t) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/e228a575925b03ec8ceee7da2033b16ad6033a51/test/visual/test.js#L1)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Much better now, thanks! I will apply the same change to the skeleton and other components.
</blockquote></details>

Applied to the skeleton in https://github.com/vaadin/vaadin-element-skeleton/pull/35

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/72)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/visual/test.js, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/72#-KinG-9249grUH-1Et8k:-Kinw-QRFbyKVv35vH4x:b5p9mud) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/e228a575925b03ec8ceee7da2033b16ad6033a51/test/visual/test.js#L1)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Applied to the skeleton in https://github.com/vaadin/vaadin-element-skeleton/pull/35
</blockquote></details>

LGTM

Not a blocker, but now we don’t need them as separate functions, actually. :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/72#-:-KinwASeUhGkQrf7o3vT:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/72#-:-KioYrNhXHw-06x5WXWY:bnfp4nl)*

**Pull request merged**
