### PR TITLE
Adding theme/material

### PR DESCRIPTION
**Pull request by manolo**
Connected to vaadin/vaadin-material-styles#49

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/232)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[theme/material/vaadin-text-area-styles.html, line 1 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field/232#-LEONLlZ5SXqMtX2VjkQ:-LEONLlZ5SXqMtX2VjkR:b812p4c) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/88ba3af823325181f42b1a335a43f3bba0a7283f/theme/material/vaadin-text-area-styles.html#L1)):*
> ```HTML
> <link rel="import" href="vaadin-text-field.html">
> ```

Why is vaadin-text-field imported here? Compare: https://github.com/vaadin/vaadin-text-field/blob/p3-preview/theme/lumo/vaadin-text-area-styles.html

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/232)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/material/vaadin-text-area-styles.html, line 1 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field/232#-LEONLlZ5SXqMtX2VjkQ:-LEO_mgK1-OBJchAuh9r:b-5j7duf) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/88ba3af823325181f42b1a335a43f3bba0a7283f/theme/material/vaadin-text-area-styles.html#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why is vaadin-text-field imported here? Compare: https://github.com/vaadin/vaadin-text-field/blob/p3-preview/theme/lumo/vaadin-text-area-styles.html
</blockquote></details>

it was in original theme, changed to import the styles file instead

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/232)*

**Comment by tomivirkki** [comment]
*[theme/material/vaadin-text-area-styles.html, line 1 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field/232#-LEONLlZ5SXqMtX2VjkQ:-LEOVGUX7EMF-zjfuJ18:b-g8np83) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/88ba3af823325181f42b1a335a43f3bba0a7283f/theme/material/vaadin-text-area-styles.html#L1)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

it was in original theme, changed to import the styles file instead
</blockquote></details>

Password field also

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/232)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/material/vaadin-text-area-styles.html, line 1 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field/232#-LEONLlZ5SXqMtX2VjkQ:-LEOc0Se1RI9SUsLVsJk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/88ba3af823325181f42b1a335a43f3bba0a7283f/theme/material/vaadin-text-area-styles.html#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Password field also
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/232)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/232#-:-LEOc5P07TfMgfLgtUah:bnfp4nl)*

**Pull request merged**
