### PR TITLE
Add autocapitalize attribute

### LINKED ISSUE #150: Support `autocapitalize` attribute
https://developers.google.com/web/updates/2015/04/autocapitalize

### PR DESCRIPTION
**Pull request by heruan**
Fixes #150.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/190)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-text-field-mixin.html, line 121 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/190#-L2tQqnQzUQnatYykOcy:-L2tQqnQzUQnatYykOcz:bq7fepy) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/9138893b6c587e3ce4c198e65604209630b78080/src/vaadin-text-field-mixin.html#L121)):*
> ```HTML
> 
>           /**
>            * This is a property supported by Safari that is used to control whether
> ```

nit: also available in Chrome at least for text field: https://www.chromestatus.com/feature/4529989986811904

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/190)*

**Comment by heruan** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-text-field-mixin.html, line 121 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/190#-L2tQqnQzUQnatYykOcy:-L2tTEFHN_mc4gw8_m_i:b489uma) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/9138893b6c587e3ce4c198e65604209630b78080/src/vaadin-text-field-mixin.html#L121)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: also available in Chrome at least for text field: https://www.chromestatus.com/feature/4529989986811904
</blockquote></details>

Added Chrome to the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/190)*

**Comment by web-padawan** [comment]
BTW the funny thing is that we already use the `autocapitalize` attribute in `vaadin-combo-box`: https://github.com/vaadin/vaadin-combo-box/blob/master/src/vaadin-combo-box.html#L72

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-text-field-mixin.html, line 127 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/190#-L33UxB1kOmNP7huksOg:-L33UxB2hpOGi6rN5kJM:b58n1h6) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/9138893b6c587e3ce4c198e65604209630b78080/src/vaadin-text-field-mixin.html#L127)):*
> ```HTML
>            * words: Words capitalization.
>            * sentences: Sentences capitalization.
>            * off: No capitalization.
> ```

BTW the MDN states that `off` is deprecated in favor of `none`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocapitalize

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/190#-:-L33VGYONwVta8mJsw8B:bd135ma)*

**Comment by heruan** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-text-field-mixin.html, line 127 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/190#-L33UxB1kOmNP7huksOg:-L33gox6nme6fbOIKhvT:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/9138893b6c587e3ce4c198e65604209630b78080/src/vaadin-text-field-mixin.html#L127)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW the MDN states that `off` is deprecated in favor of `none`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocapitalize
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/190)*

**Comment by platosha** [comment]
This was merged manually because of conflicts with master. Thanks for your PR anyway!

**Pull request closed without merging**
