### PR TITLE
Throw error when used with wrong Polymer version

### PR DESCRIPTION
**Pull request by samiheikki**
Connected to https://github.com/vaadin/components-team-tasks/issues/251

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/96)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 137 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/96#-KlMrMjsljJVyq4j4LW6:-KlMrMjsljJVyq4j4LW7:b-wqp2b3) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/e50b5d6209fc3620409855f405b7618f2380b4da/vaadin-text-field.html#L137)):*
> ```HTML
> 
>   <script>
>     if (!Polymer.Element) {
> ```

Couldn't Polymer be defined at this point if `polymer.html` is loaded asynchronoulsy ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/96)*

**Comment by samiheikki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 137 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/96#-KlMrMjsljJVyq4j4LW6:-KlMtdResVa1vKc5C8jF:b-cdea3o) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/e50b5d6209fc3620409855f405b7618f2380b4da/vaadin-text-field.html#L137)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Couldn't Polymer be defined at this point if `polymer.html` is loaded asynchronoulsy ?
</blockquote></details>

Do you mean `Polymer` might be undefined? In that case it would fail on `Uncaught ReferenceError: Polymer is not defined` error which would give a developer good feedback that what went wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/96)*

**Comment by limonte** [comment]
We have agreed that if any common change passed CR for the skeleton, then you can commit it for all components w/o CR.

This change was approved by 3 team members, feel free to merge this PR and commit to master for other components.

:+1:

**Comment by samiheikki** [comment]
Ah good to know, thanks @limonte

**Pull request merged**
