### PR TITLE
Fix API docs

### PR DESCRIPTION
**Pull request by Saulis**
Connects to https://github.com/vaadin/components-team-tasks/issues/239

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/61)

### CODE REVIEW

**Comment by manolo** [comment]
I would add some mechanism for the CI warning when the documentation.json is out of sync. 
That would imply a gulp task to run `polymer analyze > foo.json && diff documentation.json foo.json -q` and a dependency for polymer

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/61#-:-KhRIELFX0lqPbI9O0IF:b-oarlwe)*

**Comment by manolo** [comment]
I meant a travis task, not necessary gulp.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/61#-:-KhRJ4R9FPW8K4kAG6RP:bvp58ni)*

**Comment by platosha** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vaadin-text-field.html, line 116 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/61#-KhRKHkfBT38r-AfzC0D:-KhRKHkfBT38r-AfzC0E:b-7ngx68) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/216e9b3d3a3073bdabe80739347494f913158bb6/vaadin-text-field.html#L116)):*
> ```HTML
>      * @demo demo/index.html
>      */
>     class VaadinTextFieldElement extends Vaadin.ControlStateMixin(Vaadin.FormElementMixin(Vaadin.ThemableMixin(Polymer.Element))) {
> ```

Now can we move the element classes into `Vaadin` namespace, finally? For example:

```html
window.Vaadin = window.Vaadin || {};

Vaadin.TextFieldElement = class VaadinTextFieldElement extends /* ... */ {
  /* ... */
};
```

The API doc page was a blocker for that previously.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/61)*

**Comment by platosha** [comment]
Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/61)*

**Comment by Saulis** [comment]
the json file includes line numbers which would make the check break basically on each change unless we do some additional processing to diff only the relevant parts. 

As this element is hopefully temporary and will get replaced with iron-component-page before we hit stable, I wouldn't add anything more than is necessary to display the API docs.

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/61#-:-KhROD52kwFK-Rg5i_Gy:bhhpfjv)*

**Comment by Saulis** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-text-field.html, line 116 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/61#-KhRKHkfBT38r-AfzC0D:-KhWXhz6x0-QvpTfGnkj:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/216e9b3d3a3073bdabe80739347494f913158bb6/vaadin-text-field.html#L116)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Now can we move the element classes into `Vaadin` namespace, finally? For example:

```html
window.Vaadin = window.Vaadin || {};

Vaadin.TextFieldElement = class VaadinTextFieldElement extends /* ... */ {
  /* ... */
};
```

The API doc page was a blocker for that previously.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/61)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/61#-:-KhWYu1bALrJqiQFzrNq:bnfp4nl)*

**Pull request merged**
