### PR TITLE
Add a "label-suffix" slot

### PR DESCRIPTION
**Pull request by heruan**
Implementation of #212.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/213)

### CODE REVIEW

**Comment by tomivirkki** [comment]
I would suggest you to write a custom extension for this feature instead. Including this feature in the core text-field element would require a lot of consideration regarding Lumo/Material themes and since it's a new feature and also could be considered a breaking change, this can't be included during the ongoing beta period.

**Comment by tomivirkki** [comment]
A breaking change would in practice require a new major release so unfortunately it's unlikely to make it in `<vaadin-text-field>` 2.X.

**Comment by heruan** [comment]
I tried to avoid breaking changes, in fact I don't understand entirely which part of the changes you consider would break existing code using the element. I'm wrapping the `label` part in a `div`, but `part="label"` is still targetable, so existing themes unaware of the wrapper shouldn't break.

**Comment by heruan** [comment]
@tomivirkki any feedback about what may break merging this PR? I'm willing to try to rework this, if the feature is something you'd consider at least.

**Comment by heruan** [comment]
FWIW, I just fixed the label size issue for `vaadin-text-area` in the latest commit (not showing up here since the PR is closed now).

**Pull request closed without merging**
