### PR TITLE
Add vaadin-text-area

### PR DESCRIPTION
**Pull request by samiheikki**
Connects to https://github.com/vaadin/vaadin-core/issues/101

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/153)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Is this an initial PR or the final thing? It seems to be missing the "multi-line" feature described in https://github.com/vaadin/vaadin-core/issues/101 (implemented in paper-textarea)

---

Review status: 0 of 28 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[vaadin-text-area.html, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-KwZR6o2oMHjo3c_qp-n:-KwZR6o2oMHjo3c_qp-o:b-741tdw) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/3066da35cd5eac27956107ba620f41fa3de26308/vaadin-text-area.html#L14)):*
> ```HTML
> <dom-module id="vaadin-text-area-default-theme" theme-for="vaadin-text-area">
>   <template>
>     <style>
> ```

Wondering if the default theme could include `vaadin-text-field-default-theme` so the styles could also be reused?

---

*[vaadin-text-area.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-KwZQ5FS5xUm9JvZzVKS:-KwZQ5FS5xUm9JvZzVKT:b-jkqafw) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/3066da35cd5eac27956107ba620f41fa3de26308/vaadin-text-area.html#L153)):*
> ```HTML
>        * ----------------|----------------
>        * `label` | The label element
>        * `value` | The input element
> ```

Should this say "The textarea element"? Textarea is also an input element so in a sense this is ok as it is.

---

*[vaadin-text-area.html, line 173 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-KwZQF8J5Io0lrEzrXWi:-KwZQF8J5Io0lrEzrXWj:b-z3y8ix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/3066da35cd5eac27956107ba620f41fa3de26308/vaadin-text-area.html#L173)):*
> ```HTML
>        * @demo demo/index.html
>        */
>       class TextAreaElement extends Vaadin.ControlStateMixin(Vaadin.FormElementMixin(Vaadin.ThemableMixin(Polymer.Element))) {
> ```

Is there a reason the class isn't extending `Vaadin.TextFieldElement`? Vaadin-text-area should have its own template with a `<textarea>` (as it already does) but the code from `Vaadin.TextFieldElement` could be reused, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-:-KwZPfZBgyfzScaXwbwH:b-196fz0)*

**Comment by samiheikki** [comment]
Added multi-line feature

---

Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-text-area.html, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-KwZR6o2oMHjo3c_qp-n:-Kx23C0x6w6ESwsjVTbW:b-z5dt04) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/3066da35cd5eac27956107ba620f41fa3de26308/vaadin-text-area.html#L14)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Wondering if the default theme could include `vaadin-text-field-default-theme` so the styles could also be reused?
</blockquote></details>

Text-area has parts like `text-area` that the text-field does not have. I'm unsure if it is possible

---

*[vaadin-text-area.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-KwZQ5FS5xUm9JvZzVKS:-Kx23PXHVpSEZ8Rzt0Hv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/3066da35cd5eac27956107ba620f41fa3de26308/vaadin-text-area.html#L153)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should this say "The textarea element"? Textarea is also an input element so in a sense this is ok as it is.
</blockquote></details>

Done.

---

*[vaadin-text-area.html, line 173 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-KwZQF8J5Io0lrEzrXWi:-Kx23QpSvkU7s_s65CjE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/3066da35cd5eac27956107ba620f41fa3de26308/vaadin-text-area.html#L173)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is there a reason the class isn't extending `Vaadin.TextFieldElement`? Vaadin-text-area should have its own template with a `<textarea>` (as it already does) but the code from `Vaadin.TextFieldElement` could be reused, right?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-:-Kx23Tp6pX-bOZhm9G6U:b-gy2ual)*

**Comment by tomivirkki** [comment]
The multi-line feature needs some adjustment. It currently only auto-resizes on manual line break but doesn't handle text wrapping.

Take a look at the "autoresizing textarea input" demo at https://www.webcomponents.org/element/PolymerElements/paper-input/demo/demo/index.html
If you type in really long text (without manual line breaks), the element adapts its size automatically when the text wraps.

See how the feature is implemented in [iron-autogrow-textarea](https://github.com/PolymerElements/iron-autogrow-textarea/blob/master/iron-autogrow-textarea.html).

Iron-autogrow-textarea demo at: https://www.webcomponents.org/element/PolymerElements/iron-autogrow-textarea/demo/demo/index.html

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-:-Kx291gxtx9QNz3NLYsa:b-76bwi4)*

**Comment by tomivirkki** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[vaadin-text-area.html, line 99 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2JGDGLRL_OClSNuKL:-Kx2JGDGLRL_OClSNuKM:buwhejb) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L99)):*
> ```HTML
>       <label part="label" on-click="focus" id="[[_labelId]]">[[label]]</label>
> 
>       <div part="text-area">
> ```

I think this part should still be called "input-field"

---

*[vaadin-text-area.html, line 103 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2L7BFpX-oT3fTSMqi:-Kx2L7BFpX-oT3fTSMqj:bsvx2a) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L103)):*
> ```HTML
>         <slot name="prefix"></slot>
> 
>         <textarea part="value"
> ```

Some of the unsupported property bindings were dropped in the process. However, those properties are still present in `<vaadin-text-area>` public APIs which isn't ok. Should probably extract `vaadin-text-field-mixin` from `<vaadin-text-field>` so that the shared mixin would only contain features that both `<vaadin-text-field>` and `<vaadin-text-area>` support.

---

*[vaadin-text-area.html, line 108 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2Ku4vl0ndQLD4Oz14:-Kx2Ku4vl0ndQLD4Oz15:b-mp9ytw) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L108)):*
> ```HTML
>             disabled$="[[disabled]]"
>             maxlength$="[[maxlength]]"
>             minlength$="[[minlength]]"
> ```

`<textarea>` doesn't support this attribute

---

*[vaadin-text-area.html, line 125 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2JSXteQttEn20nGyG:-Kx2JSXteQttEn20nGyH:b1c2y87) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L125)):*
> ```HTML
> 
>       </div>
>       
> ```

nit: spaces

---

*[vaadin-text-area.html, line 150 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2KcCK0EKipDJf8dYs:-Kx2KcCK0EKipDJf8dYt:bssnzu2) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L150)):*
> ```HTML
>        * Custom property | Description | Default
>        * ----------------|-------------|-------------
>        * `--vaadin-text-area-line-height` | Property that determines the line height of the textarea element | `1`
> ```

It doesn't assign the textarea element's line height currently. The properties could use tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153)*

**Comment by samiheikki** [comment]
Review status: 0 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-text-area.html, line 99 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2JGDGLRL_OClSNuKL:-Kx2vzaI7uweT2VOgRD5:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L99)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I think this part should still be called "input-field"
</blockquote></details>

Done.

---

*[vaadin-text-area.html, line 103 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2L7BFpX-oT3fTSMqi:-Kx301_KSY8PgOsdzXzW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L103)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Some of the unsupported property bindings were dropped in the process. However, those properties are still present in `<vaadin-text-area>` public APIs which isn't ok. Should probably extract `vaadin-text-field-mixin` from `<vaadin-text-field>` so that the shared mixin would only contain features that both `<vaadin-text-field>` and `<vaadin-text-area>` support.
</blockquote></details>

Done.

---

*[vaadin-text-area.html, line 108 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2Ku4vl0ndQLD4Oz14:-Kx2wL3yyYE-GArtPisM:bemxac2) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L108)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

`<textarea>` doesn't support this attribute
</blockquote></details>

Should be supported https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

---

*[vaadin-text-area.html, line 125 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2JSXteQttEn20nGyG:-Kx2wSl4kD3E-sK5lq27:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L125)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

nit: spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153)*

**Comment by samiheikki** [comment]
Ok. Looking at them more, I'll get back on that later.

---

Review status: 0 of 17 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-:-Kx33nc9ADLBmHdIynFL:bofff93)*

**Comment by samiheikki** [comment]
Review status: 0 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-text-area.html, line 150 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2KcCK0EKipDJf8dYs:-Kx3DKdRWmlFz7T0nFbN:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L150)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

It doesn't assign the textarea element's line height currently. The properties could use tests
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153)*

**Comment by samiheikki** [comment]
Fixed multi-line resizing

---

Review status: 0 of 35 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-:-Kx8ctLDYwBA0JD3EXzn:b-7q9hgo)*

**Comment by tomivirkki** [comment]
*[vaadin-text-area.html, line 108 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2Ku4vl0ndQLD4Oz14:-Kx8uDHaJBJsybw1Xf2X:b412ci0) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L108)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Should be supported https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea
</blockquote></details>

Ah, so it seems

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153)*

**Comment by tomivirkki** [comment]
Review status: 0 of 35 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[vaadin-text-area.html, line 150 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2KcCK0EKipDJf8dYs:-Kx8ySS7K9p7GhYgY9-U:bh77zhy) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L150)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still doesn't quite work

---

*[vaadin-text-area.html, line 18 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx8wE4rn2YYgICkUGz8:-Kx8wE4rn2YYgICkUGz9:b-jku70x) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/0d1af45b289a4041edc67a09578aec7bd32a5170/vaadin-text-area.html#L18)):*
> ```HTML
>         min-width: 175px;
>         outline: none;
>         line-height: var(--vaadin-text-area-line-height​​, 1.5);
> ```

We only want to target the textarea element's line-height (as the property's description says)

---

*[vaadin-text-area.html, line 87 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx8xljtYYItHFYNCTq3:-Kx8xljtYYItHFYNCTq4:b-mol143) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/0d1af45b289a4041edc67a09578aec7bd32a5170/vaadin-text-area.html#L87)):*
> ```HTML
> 
>       </div>
>       <div id="mirror" class="mirror-text" aria-hidden="true"></div>
> ```

If someone adds styles to [part="value"] element, mirror might no longer share the same sizing. Should probably add part="value" to the mirror also.

Would drop the id from mirror (to avoid id conflicts in shady mode).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153)*

**Comment by samiheikki** [comment]
Review status: 0 of 35 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-text-area.html, line 150 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2KcCK0EKipDJf8dYs:-KxDd4Fe9gKaG_VFofm8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L150)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Still doesn't quite work
</blockquote></details>

Done.

---

*[vaadin-text-area.html, line 18 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx8wE4rn2YYgICkUGz8:-KxDX11MwLeWB9ofM97Z:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/0d1af45b289a4041edc67a09578aec7bd32a5170/vaadin-text-area.html#L18)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

We only want to target the textarea element's line-height (as the property's description says)
</blockquote></details>

Done.

---

*[vaadin-text-area.html, line 87 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx8xljtYYItHFYNCTq3:-KxDda7MQ06H0SJPbmbT:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/0d1af45b289a4041edc67a09578aec7bd32a5170/vaadin-text-area.html#L87)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

If someone adds styles to [part="value"] element, mirror might no longer share the same sizing. Should probably add part="value" to the mirror also.

Would drop the id from mirror (to avoid id conflicts in shady mode).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153)*

**Comment by tomivirkki** [comment]
The tests aren't passing on Edge and IE11

---

Review status: 0 of 41 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-text-area.html, line 150 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Kx2KcCK0EKipDJf8dYs:-KxGMmWzKqdI1TCxzAXv:b-n9unr1) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/fc01fb3a53087b33c32b711c4360548040bbe543/vaadin-text-area.html#L150)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Works on Chrome but at least Edge is still not getting the right value (could use a test). Same thing with `--vaadin-text-area-max-height`.

---

*[demo/text-area-demos.html, line 24 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-KxGQX9NmaTpikSWyGN2:-KxGQX9NmaTpikSWyGN3:b-fsm2ho) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/220c44bc078d9a0ef3a2a4eec0493b39fdbdf54a/demo/text-area-demos.html#L24)):*
> ```HTML
>       <template preserve-content>
>         <style>
>           vaadin-text-area {
> ```

The selectors aren't scoped so the styles leak outside in polyfilled browsers. This is visible in Firefox.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-:-KxGMEsWbXLy4CSBzrY0:bkhc1zw)*

**Comment by samiheikki** [comment]
Review status: 0 of 41 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/text-area-demos.html, line 24 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-KxGQX9NmaTpikSWyGN2:-KxGeKRCPY35hR_b_v65:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/220c44bc078d9a0ef3a2a4eec0493b39fdbdf54a/demo/text-area-demos.html#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The selectors aren't scoped so the styles leak outside in polyfilled browsers. This is visible in Firefox.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153)*

**Comment by tomivirkki** [comment]
Did some prototyping on how `min-height`, `max-height` and `line-height` could be applied as standard CSS without needing all the calculation. Not sure if this covers all the cases but at least the demos seem to work nicely. Take a look. If all looks good, feel free to merge and continue from there. The PR: https://github.com/vaadin/vaadin-text-field/pull/155

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-:-KxmYUAeQ23tmDA5nG2A:b16odc3)*

**Comment by YuriyVaadin** [comment]
Reviewed 3 of 33 files at r1, 3 of 25 files at r2, 4 of 30 files at r4, 6 of 34 files at r5, 18 of 28 files at r6, 68 of 82 files at r9.
Review status: 57 of 68 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 5 of 33 files at r1, 2 of 6 files at r3, 1 of 34 files at r5, 1 of 8 files at r8, 2 of 82 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-:-KxxbRCdTwSKoU4nHSt6:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 7 of 33 files at r1, 3 of 30 files at r4, 1 of 28 files at r6, 65 of 82 files at r9, 13 of 14 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-:-Kxy9bnXxEZruq-cB2Ck:bnfp4nl)*

**Comment by manolo** [comment]
Very good job guys!.

I have a question, in native text-area there is a handler for the user to resize the area, that is useful in desktop, is that a feature we need to implement? 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[vaadin-text-area.html, line 129 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Ky-Xt5HTqmh0j8krf2F:-Ky-Xt5HTqmh0j8krf2G:b-1hwu63) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5bcc6c93e4c5723c5d20f1c49501005ac5cbdeb6/vaadin-text-area.html#L129)):*
> ```HTML
>        * @demo demo/index.html
>        */
>       class TextAreaElement extends Vaadin.TextFieldMixin(Vaadin.ThemableMixin(Polymer.Element)) {
> ```

This class is still quite identical  to `vaadin-text-field` except from the updateHeight,  IMO is so much duplicated code in the project, I would suggest to share the code via the mixin `_valueChanged` , `checkValidity` , `ready`

---

*[test/accessibility.html, line 44 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Ky-ZyrklOsXzA2orj5q:-Ky-ZyrklOsXzA2orj5r:b-xzg38e) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5bcc6c93e4c5723c5d20f1c49501005ac5cbdeb6/test/accessibility.html#L44)):*
> ```HTML
>       </template>
>     </test-fixture>
>   
> ```

Nit: there are for occurrences of empty lines with spaces in this file

---

*[test/accessibility.html, line 152 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Ky-_EndBsNhTZ3pzxkU:-Ky-_EndBsNhTZ3pzxkV:bxq3pie) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5bcc6c93e4c5723c5d20f1c49501005ac5cbdeb6/test/accessibility.html#L152)):*
> ```HTML
>           let tf, err, input;
> 
>           beforeEach(function() {
> ```

We are still using functions instead of lambdas in this project's tests. Just for remembering we need to migrate, but in separated PR. No blocker

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-:-Ky-_i9ag5hIkI6RqCA5:b-6fma5z)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/accessibility.html, line 44 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Ky-ZyrklOsXzA2orj5q:-Ky-aokKbsfO6IWy0HoV:b-xk1287) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5bcc6c93e4c5723c5d20f1c49501005ac5cbdeb6/test/accessibility.html#L44)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Nit: there are for occurrences of empty lines with spaces in this file
</blockquote></details>

/for/four/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153)*

**Comment by tomivirkki** [comment]
> I have a question, in native text-area there is a handler for the user to resize the area, that is useful in desktop, is that a feature we need to implement?

The feature has been explicitly disabled from `<vaadin-text-area>`. It’s only supported on a limited set of browsers so if we want that feature (later), we’ll need to implement it ourselves.

---

Review status: 65 of 70 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-text-area.html, line 129 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Ky-Xt5HTqmh0j8krf2F:-Ky-oqCqj6m0-5ulsC04:b-5ikoco) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5bcc6c93e4c5723c5d20f1c49501005ac5cbdeb6/vaadin-text-area.html#L129)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This class is still quite identical  to `vaadin-text-field` except from the updateHeight,  IMO is so much duplicated code in the project, I would suggest to share the code via the mixin `_valueChanged` , `checkValidity` , `ready`
</blockquote></details>

Excellent point. Removed lots of duplicated code.

---

*[test/accessibility.html, line 44 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Ky-ZyrklOsXzA2orj5q:-Ky-pVBJ2KcMnmzcdSWa:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5bcc6c93e4c5723c5d20f1c49501005ac5cbdeb6/test/accessibility.html#L44)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

/for/four/
</blockquote></details>

Done.

---

*[test/accessibility.html, line 152 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-Ky-_EndBsNhTZ3pzxkU:-Ky-pdtLD0cXimYl13_p:b-ic8ucs) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5bcc6c93e4c5723c5d20f1c49501005ac5cbdeb6/test/accessibility.html#L152)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

We are still using functions instead of lambdas in this project's tests. Just for remembering we need to migrate, but in separated PR. No blocker
</blockquote></details>

True, I'll leave this outside of this already big PR though. Can be fixed in separate cleanup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-:-Ky-mHOcFWUtMNDAPh4F:b-u3lndf)*

**Comment by tomivirkki** [comment]
Reviewed 5 of 5 files at r11.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/153#-:-Ky0D53qhjnzJj1hUQ9L:bnfp4nl)*

**Pull request merged**
