### PR TITLE
P3 preview dev

### LINKED ISSUE #205: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #205

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/211)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 17 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.travis.yml, line 22 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-text-field/211#-L8frAor8mtLdel_kqbH:-L8frAor8mtLdel_kqbI:bcydhz5) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/9ef737ad89e36df094a1dba19c08113372db3859/.travis.yml#L22)):*
> ```YAML
>   - TEST_SUITE=polyfilled, POLYMER=2
>   - TEST_SUITE=desktop, POLYMER=2
>   - TEST_SUITE=saucelabs-p3, POLYMER=3
> ```

Use space: https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices

Btw same as in bash and zsh command line.

Otherwise commas are treated as part of the value: https://travis-ci.org/vaadin/vaadin-text-field/jobs/359259468#L452

---

*[test/validation.html, line 48 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-text-field/211#-L8frhyJ5LxdW_PnzxEe:-L8frhyJ5LxdW_PnzxEf:bpc12gr) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/9ef737ad89e36df094a1dba19c08113372db3859/test/validation.html#L48)):*
> ```HTML
>           input = tf.focusElement;
>           animationFrameFlush(() => {
>             setTimeout(done, 100);
> ```

BTW is `setTimeout` necessary? WCT should ensure tests are not running before all dependencies are ready.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-text-field/211)*

**Comment by YuriyVaadin** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 22 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-text-field/211#-L8frAor8mtLdel_kqbH:-L8fzoXP5MH4ga6ICwdG:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/9ef737ad89e36df094a1dba19c08113372db3859/.travis.yml#L22)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Use space: https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices

Btw same as in bash and zsh command line.

Otherwise commas are treated as part of the value: https://travis-ci.org/vaadin/vaadin-text-field/jobs/359259468#L452
</blockquote></details>

Done.

---

*[test/validation.html, line 48 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-text-field/211#-L8frhyJ5LxdW_PnzxEe:-L8fzp2I2xOVqHdSwK3G:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/9ef737ad89e36df094a1dba19c08113372db3859/test/validation.html#L48)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW is `setTimeout` necessary? WCT should ensure tests are not running before all dependencies are ready.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-text-field/211)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-text-field/211)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-text-field/211#-:-L8g5Vbn01EmsAS2KS-Y:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 15 of 18 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-text-field/211#-:-L8g5fch6Hq6x9acd1EN:bnfp4nl)*

**Pull request merged**
