### PR TITLE
Prefix classes, remove id='input' to avoid collisions

### PR DESCRIPTION
**Pull request by limonte**
Connected to https://github.com/vaadin/components-team-tasks/issues/280

Fixes https://gitlab.vaadin.com/vaadincom/webpage/issues/1764

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/142)

### CODE REVIEW

**Comment by tomivirkki** [comment]
:lgtm: But the tests should pass

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/142#-:-KuJovUv1a57qwZuGziE:b21sq1u)*

**Comment by limonte** [comment]
Tests are broken not because of this change. Master is broken as well after `control-state-mixin` latest tag: https://travis-ci.org/vaadin/vaadin-text-field/builds/276511395

**Comment by tomivirkki** [comment]
Ah, yes, not related to this PR

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/142#-:-KuJwwpr9lZoXvo_KmMe:bt1664c)*

**Comment by tomivirkki** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/142)*

**Pull request merged**
