### PR TITLE
Restructure demos (plus minor theme updates)

### PR DESCRIPTION
**Pull request by jouni**
### Examples

- Remove tabindex example (not a best practice)

- Remove data binding example (Polymer specific, not a text field
feature)

- Hide iron-form example (couldn’t get it to work). Can be added back
later if the binding scope is working

- Extract prefix and suffix examples (including icons) and RTL example
to separate pages

- Add a styling examples, which includes probably the most common
customizations (input field border and background)

- Extract all validation related examples into a separate page

- Remove “contrast” example from Valo theme examples

### Element themes

- Refactor text alignment to be a theme variation, not a CSS custom
property (allows other customizations that rely on this, such as the
mask image)

- Add a CSS custom property for hiding the password field reveal button

- Adjust the password field default width to match text field and text
area

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field/179)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[demo/index.html, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-L0hoPtkHKGX3Z8uGEMm:-L0hoPtlXOPlvvjcGaXD:b-mumchu) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5498878d96085d227f54344152325e8cfab78b53/demo/index.html#L30)):*
> ```HTML
>   <vaadin-component-demo config-src="demos.json"></vaadin-component-demo>
> 
>   
> ```

What is the reason to have this code duplicated both here and in the Styling examples?
Can we place it into a separate HTML import?

---

*[demo/index.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-L0hoaHn8o-7Fckep416:-L0hoaHn8o-7Fckep417:b-uet2hb) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5498878d96085d227f54344152325e8cfab78b53/demo/index.html#L35)):*
> ```HTML
>       <style>
>         :host(.custom-style) [part="input-field"] {
>           border: 1px solid #CCC;
> ```

BTW maybe we should use lowercase hex? We currently don't have this rule in our `stylelint` config but the standard config includes it.

---

*[demo/text-field-basic-demos.html, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-L0hpSOC7Yj1UXC3iqfz:-L0hpSOC7Yj1UXC3iqg-:b8lhc6q) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5498878d96085d227f54344152325e8cfab78b53/demo/text-field-basic-demos.html#L34)):*
> ```HTML
>       <template preserve-content>
>         <vaadin-text-field value="left"></vaadin-text-field>
>         <vaadin-text-field value="center" theme="align-center"></vaadin-text-field>
> ```

These themes are Valo-specific and therefore the demo should probably go to the Valo theme variations tab.

---

*[demo/text-field-styling-demos.html, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-L0hprU5CGovlmoMrA0d:-L0hprU5CGovlmoMrA0e:b-dp16sq) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5498878d96085d227f54344152325e8cfab78b53/demo/text-field-styling-demos.html#L12)):*
> ```HTML
> 
>     <h3>Custom Border and Background</h3>
>     <vaadin-demo-snippet id="text-field-styling-demos-border-styles">
> ```

nit: duplicate `vaadin-demo-snippet` opening tag

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179)*

**Comment by jouni** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[demo/index.html, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-L0hoPtkHKGX3Z8uGEMm:-L0i4HyMPGz8544mYN4u:b-n09drx) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5498878d96085d227f54344152325e8cfab78b53/demo/index.html#L30)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

What is the reason to have this code duplicated both here and in the Styling examples?
Can we place it into a separate HTML import?
</blockquote></details>

I want to have the code visible for the site visitor. But the element is registered before this dom-module is active, so it doesn’t get picked up by `ThemableMixin`.

Any suggestions how to avoid the duplication?

---

*[demo/index.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-L0hoaHn8o-7Fckep416:-L0i4WfMjIbG5Imtsqqg:b-stjs3z) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5498878d96085d227f54344152325e8cfab78b53/demo/index.html#L35)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW maybe we should use lowercase hex? We currently don't have this rule in our `stylelint` config but the standard config includes it.
</blockquote></details>

Sure, will change. For some reason, I changed these to uppercase, thought it was a more common practice.

---

*[demo/text-field-basic-demos.html, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-L0hpSOC7Yj1UXC3iqfz:-L0i4e1cv8YdWWMZQoZB:b6ef97) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5498878d96085d227f54344152325e8cfab78b53/demo/text-field-basic-demos.html#L34)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

These themes are Valo-specific and therefore the demo should probably go to the Valo theme variations tab.
</blockquote></details>

Absolutely correct. I’ll move them to Valo examples now. I think we should consider having these as built-in.

---

*[demo/text-field-styling-demos.html, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-L0hprU5CGovlmoMrA0d:-L0i4uyeAbBG5aIuUss8:bn7zm4v) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5498878d96085d227f54344152325e8cfab78b53/demo/text-field-styling-demos.html#L12)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: duplicate `vaadin-demo-snippet` opening tag
</blockquote></details>

🤦‍♂️ will remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179)*

**Comment by jouni** [comment]
Review status: 10 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/text-field-basic-demos.html, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-L0hpSOC7Yj1UXC3iqfz:-L0i7-h3TJSAxqb3zZBV:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5498878d96085d227f54344152325e8cfab78b53/demo/text-field-basic-demos.html#L34)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Absolutely correct. I’ll move them to Valo examples now. I think we should consider having these as built-in.
</blockquote></details>

Done.

---

*[demo/text-field-styling-demos.html, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-L0hprU5CGovlmoMrA0d:-L0i6lF9_sNqSKRSVk2m:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5498878d96085d227f54344152325e8cfab78b53/demo/text-field-styling-demos.html#L12)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

🤦‍♂️ will remove.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179)*

**Comment by web-padawan** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demo/index.html, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-L0hoPtkHKGX3Z8uGEMm:-L0iTFh5r_gnuCjLG07w:b-5zj9bq) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5498878d96085d227f54344152325e8cfab78b53/demo/index.html#L30)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

I want to have the code visible for the site visitor. But the element is registered before this dom-module is active, so it doesn’t get picked up by `ThemableMixin`.

Any suggestions how to avoid the duplication?
</blockquote></details>

We probably could try to add some code to inject that snippet dynamically using `Polymer.DomModule.import` but I am not quite sure if `marked-element` used internally by `vaadin-demo-snippet` supports this kind of mutation. @tomivirkki WDYT?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 7 of 14 files at r1, 2 of 4 files at r2, 6 of 6 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demo/index.html, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-L0hoPtkHKGX3Z8uGEMm:-L0sWJKwLrNTQXkrmtet:b-q2eibt) ([raw file](https://github.com/vaadin/vaadin-text-field/blob/5498878d96085d227f54344152325e8cfab78b53/demo/index.html#L30)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

We probably could try to add some code to inject that snippet dynamically using `Polymer.DomModule.import` but I am not quite sure if `marked-element` used internally by `vaadin-demo-snippet` supports this kind of mutation. @tomivirkki WDYT?
</blockquote></details>

Maybe a feature for the demo snippet. Not urgent IMO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-:-L0sWb5ejQPpjdhje5vP:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-:-L0t02wiqsOGBBSSKbut:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 7 of 14 files at r1, 2 of 4 files at r2, 4 of 6 files at r3, 4 of 4 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179#-:-L0t1hQ3WU9b088KuLqg:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field/179)*

**Pull request merged**
